### ISSUE TITLE
oota chp4 succubus needs linking near bottom.

### ISSUE THREAD

**Issue by l9f** [TheGiddyLimit/TheGiddyLimit.github.io#106]

**Comment by TheGiddyLimit** [comment]
Could you perhaps keep all these in one issue, please. Also, if you're planning to fix them (as I said, feel free to fix them manually, these are too specific to fix in the script) please do it in one pull request. Last time I had to spend a solid 10 minutes merging them all 😬

**Comment by l9f** [comment]
Consolidated to Issue #107. Got some questions there too.
