### ISSUE TITLE
Consolidated OOTA Chapter 4 Issues

### ISSUE THREAD

**Issue by l9f** [TheGiddyLimit/TheGiddyLimit.github.io#107]
- [x] Succubus needs linking near king
- [x] Deepking needs a bestiary entry
  - [x] Base Bestiary entry done.
  - [x] Link the adventure text to his bestiary entry.
    - [x] Resolve link display issue in comments below.
  - [x] Link in bestiary entry to gauntlets of ogre power
  - [x] Link to Madness rules for Indef Madness trait
  - [x] Deepking needs his image converted into a token (Duergar 2 image already in adventure chapter 4)
  - [x] Deepking needs to be globally searchable (how do I do that? Doesn't seem to be picking that up just from the bestiary json?)
  - [x] Global search to Deepking also link to the place in OotA where he is discussed (end of Chp 4?)
- [x] `A water weird bound to the pool years has been corrupted by the demonic influence infecting these tunnels, turning it evil and giving it a dark hunger.` Should it be `...pool for years...`?
- [x] Spider King needs a bestiary entry
  - [x] Base Bestiary entry done
  - [x] Spider King needs to be globally searchable (how do I do that? Doesn't seem to be picking that up just from the bestiary json?)
- [x] `Ten minutes before the effect ends, the creature feels a tingling sensation, at which point it can sustain its current size by eating another wurple` Shouldn't *wurple* be `bigwig`?
- [x] irruption -> eruption typo **Apparently I'm wrong; `irruption` is correct.** _See_: https://www.cjr.org/language_corner/eruption_irruption.php
- [x] Fix typo Duergar xarron -> xarrorn in bestiary.
- [x] Duergar `xarron` in global search needs to be removed and replaced with `xarrorn`
- [x] duergar xarrorn needs linking
- [x] `The foreigners confined by law to this part of the city.` looks like a word has been left out.

**Comment by l9f** [comment]
Is there a way to change the display text of a creature link? 

Running into issues with the xarrorn: The official creature name is `Duergar xarrorn` but the text frequently just says `xarrorn`; do we want to expand everything to display as `Duergar xarrorn` or come up with some syntax that allows alternate display text? i.e. generate something like `<a href=$FULL LINK}xarrorn</a>`

**Comment by l9f** [comment]
On the `wurple` issue; it's in the print text but not the errata that I have. Perhaps it's a typo they've just left out? Does wurple mean mushroom? Google doesn't even really offer anything other than urban dictionary.

**Comment by l9f** [comment]
Same with the `water weird issue`; that typo is in the text. I think we ought to use fix it by adding `for` before `years`. 

Thoughts?

**Comment by l9f** [comment]
Running into the same thing, How do I link to a creature in the bestiary with full name of `Deepking Horgar Steelshadow V` as just the `Deepking` in text for an `{@creature Deepking Horgar Steelshadow V|OotA}`?

**Comment by Temp345** [comment]
[See the renderer demo](https://thegiddylimit.github.io/demo.html).

`{@creature cow|vgm|and optional link text added with another pipe}`

**Comment by l9f** [comment]
Great thank you.

**Comment by MrLabRat** [comment]
Much of this is already solved!
