### ISSUE TITLE
Monsters Needing Tokens for R20 or otherwise

### ISSUE THREAD

**Issue by l9f** [TheGiddyLimit/TheGiddyLimit.github.io#112]
List put together 2018-01-31:

- [ ] Aerisi Kalinoth
- [ ] Air Elemental Myrmidon
- [ ] Ambush Drake
- [ ] Avatar of Death
- [ ] Awakend Zurkhwood
- [ ] Azbara Jos
- [ ] Baphomet
- [ ] Bastian Thermandar
- [ ] Black Earth Guard
- [ ] Black Earth Priest
- [ ] Black Guard Drake
- [ ] Blagothkus
- [ ] Bridesmaid of Zuggtmoy
- [ ] Burrowshark
- [ ] Captain Othelstan
- [ ] Chamberlain of Zuggtmoy
- [ ] Chuul Spore Servant
- [ ] Crushing Wave Priest
- [ ] Crushing Wave Reaver
- [ ] Dark Tide Knight
- [ ] Decapus
- [ ] Deepking Horgar Steelshadow V
- [ ] Demogorgon
- [ ] Derro
- [ ] Derro Savant
- [ ] Drannin Splithelm
- [ ] Dralmorrer Borngray
- [ ] Dragonclaw
- [ ] Dragonfang
- [ ] Dragonsoul
- [ ] Dragonwing
- [ ] Droki
- [ ] Drow Spore Servant
- [ ] Duergar Darkhaft
- [ ] Duergar Kavalrachni
- [ ] Duergar Keeper of the Flame
- [ ] Duergar Soulbalde
- [ ] Duergar Spore Servant
- [ ] Duergar Stone Guard
- [ ] Duergard Xarrorn
- [ ] Duodrone
- [ ] Earth Elemental Myrmidon
- [ ] Elizar Dryflagon
- [ ] Emerald Enclave Scout
- [ ] Eternal Flame Guardian
- [ ] Eternal Flame Priest
- [ ] Fathomer
- [ ] Feathergale Knight
- [ ] Female Steeder
- [ ] Fire Elemental Myrmidon
- [ ] Flamewrath
- [ ] Fraz-Urb'luu
- [ ] Frulam Mondath
- [ ] Gar Shatterkeel
- [ ] Geonid
- [ ] Ghald
- [ ] Giant Fly
- [ ] Giant Riding Lizard
- [ ] Giant Strider
- [ ] Graz'zt
- [ ] Guard Drake
- [ ] Hellenrae
- [ ] Hook Horror Spore Servant
- [ ] Howling Hatred Initiate
- [ ] Howling Hatred Priest
- [ ] Hurricane
- [ ] Ice Toad
- [ ] Imix
- [ ] Ixitxachitl
- [ ] Ixitcachitl Cleric
- [ ] Jamna Gleamsilver
- [ ] Juiblex
- [ ] Langdedrosa Cyanwrath
- [ ] Larva
- [ ] Lords' Alliance Guard
- [ ] Lords' Alliance Spy
- [ ] Marlos Urnrayle
- [ ] Miraj Vizann
- [ ] Narrak
- [ ] Naergoth Bladelord
- [ ] Nereid
- [ ] Neronvain
- [ ] Ogremoch
- [ ] Olhydra
- [ ] One-Eyed Shiver
- [ ] Orcus
- [ ] Oreioth
- [ ] Pharblex Spattergoo
- [ ] Rath Modar
- [ ] Rezmir
- [ ] Razerblast
- [ ] Sacred Stone Monk
- [ ] Shoalar Quanderil
- [ ] Skyweaver
- [ ] Spider King
- [ ] Stonemelder
- [ ] Severin
- [ ] Talis the White
- [ ] Tiamat
- [ ] The Pudding King
- [ ] Thunderbeast Skeleton
- [ ] Thurl Merosska
- [ ] Tiny Servant
- [ ] Topi
- [ ] Tortle Druid
- [ ] Troglodyte Champion of Laogzed
- [ ] Vampiric Ixitxachitl
- [ ] Vampiric Ixitxachitl Cleric
- [ ] Vanifer
- [ ] Veteran of the Gauntlet
- [ ] Volothamp "Volo" Geddarm
- [ ] Water Elemental Myrmidon
- [ ] Werebear
- [ ] White Guard Drake
- [ ] Wiggan Nettlebee
- [ ] Windharrow
- [ ] Yan-C-Bin
- [ ] Yeenoghu
- [ ] Yestabrod
- [ ] Zhentarim Thug
- [ ] Zuggtmoy

**Comment by MrLabRat** [comment]
That list is out of date!
[missing tokens.txt](https://github.com/TheGiddyLimit/TheGiddyLimit.github.io/files/1695383/missing.tokens.txt)
That file is up to date with the missing tokens.
