### ISSUE TITLE
[BUG] OmniSearch, can't click on links (it works on 5etools.com)

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#114]
OmniSearch's results look like links (probably still are) and hover text appears correctly,
but clicking on them simply closes the results' "window".

They work as links on 5etools.com.

EDIT: adding a detail that may or may not be relevant: mouse pointer doesn't change
when hovering on the links (maybe it actually does for a very short time).

**Comment by TheGiddyLimit** [comment]
Hadn't pushed the latest version to GitHub, is all. Should be fine now.
