### ISSUE TITLE
[Feature Request] Equipment Price & Weight Calculator

### ISSUE THREAD

**Issue by mistatipsta** [TheGiddyLimit/TheGiddyLimit.github.io#115]
Is this a bug or a feature request: Feature

Page(s) affected:
/items.html

Additional information:
A method by which users could list various weapons, armor, animals, adventuring equipment, etc to and it would automatically sum the total cost and weight.

**Comment by TheGiddyLimit** [comment]
Noted. There's a similar suggestion in the Discord [suggestions archive](https://discord.gg/rZNf5T), and certainly plans to implement this sometime in the future. Unlikely that it'll happen soon, but we'll see.
