### ISSUE TITLE
Creatures with different CR when in their Lair

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#142]
See the Mummy Lord. Its CR is 15 but when it can use Lair Actions it becomes 16.
A few other creatures do the same, I can provide a list if needed.
EDIT:

- Death Tyrant
- Demilich
- Lich
- Vampire (it's not specified how spellcaster and warrior variants are affected by being in their lair) **- EDIT: nope**
- Acererak Demilich (not its official name, it's the demilich variant currently missing in 5etools, source MM)
- Mummy Lord
- Aboleth **- EDIT: nope**
- Beholder

Not sure if the list is complete. Hags too have a different CR if encountered as a coven
(and the coven related features could be presented using the "variant" format for
better - arguably - readability).

Is there a way to display this information, possibly without having to create a 2nd entry?
Maybe in the Lair Actions "box" or maybe in the "cr row", something like:
> Challenge 15 (13,000 XP) or 16 (15000 XP) when encountered in its Lair.

**Comment by TheGiddyLimit** [comment]
Good point. Couldn't see updated CRs for vampires or aboleths, but the rest should now be visible. I'd imagine there'll be some in the other bestiary files, though, will have to check later.

**Comment by TheGiddyLimit** [comment]
Also will've broken roll20 importing for those monsters, will fiddle with that later, also.

**Comment by Temp345** [comment]
My bad about Vampire and Aboleth.

**Comment by TheGiddyLimit** [comment]
Roll20 script fixed, and added lair CRs for VGM monsters, I think. Probably some 3pp stuff to fix up still, so I'll leave this open.

**Comment by TheGiddyLimit** [comment]
3pp exiled.
