### ISSUE TITLE
[Bug] CR Calculator, some monster traits screw things up

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#146]
**EDIT: ignore this one and see the next.**

> It should increase the effective hp based on the estimated cr.
> 
> I'm getting weird issues where sometimes some things work and sometimes they don't,
> for example changing the # saving throw proficiencies sometimes changes the effective AC
> and sometimes it does not.

**Comment by Temp345** [comment]
This is probably related. Steps:
- verify that changing the **Damage per round** value changes the **Average Damage Per Round**
displayed in the "box" in the top-left corner
- tick one of the monster traits related to hp (damage transfer, frightful presence, legendary resistances, etc)
- now changing the **Damage per round** value doesn't change the **Average Damage Per Round**
displayed in the "box" in the top-left corner

**Comment by TheGiddyLimit** [comment]
Fixed, I think.
