### ISSUE TITLE
Question about monster fluff

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#147]
Does it make sense to edit the entries manually or you do plan to
improve the importing from FG modules to keep the original formatting?

Seems like the FG MM module has 19 as AC for a the drow variant with +1 armor.
You may want to fix the original to avoid having this bug every time you re-import the data.

You may have already noticed but that _appendCopy doesn't seem to work
(e.g. a Pit Fiend defining its own specific fluff then referencing the generic devils fluff).

**Comment by Temp345** [comment]
Here's a list with the monsters with a bad _appendCopy

Barlgura (**NOTE**: points to Devil instead of Demon)
Bearded Devil
Bone Devil
Chain Devil
Erinyes
Horned Devil
Ice Devil
Imp
Lemure
Pit Fiend
Spined Devil

If you want I've already fixed them all, but maybe you prefer to fix the issue by
allowing the _appendCopy to also work when inside the "entries".

**Comment by TheGiddyLimit** [comment]
They're aaaaaall going to need to be manually edited. 

Fixed the `_appendCopy` mistakes, my bad. Was watching Critical Role while making the JSON; mind-numbing work.

>for once I'm useful!
You're always useful.
