### ISSUE TITLE
Image size issues on class page

### ISSUE THREAD

**Issue by oneandonlyflexo** [TheGiddyLimit/TheGiddyLimit.github.io#159]
Is this a bug or a feature request: Bug

Issue: Images added to class/subclass entries can be extremely large.  It seems they don't have a max-width (or max-height) set.  The css rule for images on other pages that use them seem to have the rule "table.stats tr.text img".  On the class page, none of the <tr> elements have the "text" class so the image width/height rule isn't being used.  Not sure if adding new css rules specifically for images in the class page would be better or if adding the "text" class to <tr> elements in the classes would be better.

Page(s) affected: Classes

Reproduction steps:  Add this bit to any homebrew subclass entry.

> `{
> 	"type": "image",
> 	"href": {
> 		"type": "internal",
> 		"path": "adventure/OotA/Velkynvelve.jpg"
> 	},
> 	"title": "Velkynvelve Side Players"
> }`

Additional information:

Browser (Chromium, Firefox, Edge, etc): I've only tested in chrome, but I'm assuming all

Platform (Windows, iOS, Android, etc): Windows (but probably all)

**Comment by TheGiddyLimit** [comment]
Having fiddled with this in the past, there was some reason blanket-setting the CSS was causing issues, but I don't remember exactly what the reason was. Simpler, anyway, to add the `text` class. Will fix.
