### ISSUE TITLE
[bug] CR Calculator: Vulnerabilities check box not working

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#16]
Bug
Ticking or unticking the **Vulnerabilities** checkbox has no effect on the effective hp
(when checked it should halve it).
Page: crcalculator.html but the problem is likely in js/crcalculator.js

**Comment by Temp345** [comment]
There's something wrong also with resitances/immunities.
They always double the effective hp, no matter what the CR is.

**Comment by TheGiddyLimit** [comment]
Interesting. Will look into it.

Sorry I didn't see this sooner, GitHub stopped sending me email notifications. In future if I seem to have died, you can probably find me (or the exact cause of my demise) on the 5etools Discord server, linked from somewhere on the homepage.

**Comment by TheGiddyLimit** [comment]
Vulnerabilities box has been fixed. Resistances/immunities are working as intended, as far as I can tell. They base the multiplication off the value you enter in Expected CR. Perhaps another fix took care of the issue?
