### ISSUE TITLE
Export Spells as Table

### ISSUE THREAD

**Issue by RMcD94** [TheGiddyLimit/TheGiddyLimit.github.io#163]
Is this a bug or a feature request: Feature Request
Issue: Exporting Spells
Browser (Chromium, Firefox, Edge, etc): Chrome
Platform (Windows, iOS, Android, etc): Windows

I must be an idiot because I want to export specific spell lists (for example all cantrips in SCAG, PHB and XGE), preferably as a table (Name/Source/Level/Time/School/Range/Description/Components/Classes).

I've tried just copy pasting the table as it is on the website but my copypaste is not resulting in a table nor even any tab marker or commas or anything that would allow me to convert it to columns just: "Acid SplashPHBCantripActionConj.60 feet" which I don't know how to separate without manually doing it 

Appreciate any help, I assume there's an export feature somewhere and I'm just blind.

**Comment by TheGiddyLimit** [comment]
I'm afraid there's no such feature, nobody's ever requested such a thing. The "Book View" is the closest you'll get for right now (not that it's even close to what you're requesting); I'm midway through moving house, but I'll take a look at this once I'm set back up. Shouldn't be hard to add.

**Comment by TheGiddyLimit** [comment]
Finally got around to bashing something together for this:
![capture](https://user-images.githubusercontent.com/25264887/42848929-32be8754-8a19-11e8-97c5-075ca8df0621.PNG)

It'll be released with the next update, hopefully sometime in the next 24 hours.

**Comment by TheGiddyLimit** [comment]
That should be it live. If you're using the `github.io` version of the site, you'll most likely need to CTRL-F5.
