### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by elmerfudddied** [TheGiddyLimit/TheGiddyLimit.github.io#164]
Issue: Spelling Error 
Under the Hit Points and Hit Dice section, the text "if you area paladin" should be "if you are a paladin". The space is missing from between "are" and "a". The error occurs twice in this section.

Page affected: https://5etools.com/quickreference.html#quickreference,0

**Comment by TheGiddyLimit** [comment]
Will be fixed in the next update, thanks.
