### ISSUE TITLE
Chapter numbering according to map number as in books

### ISSUE THREAD

**Issue by Mathizsias** [TheGiddyLimit/TheGiddyLimit.github.io#167]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Feature request, but per the books it should be numbered.

Issue: Chapter numbering according to map number as in books.

Page(s) affected: All adventures.

Reproduction steps: -

Additional information: https://5etools.com/adventure.html#HotDQ,8 Has a village of parnast map with numbers, but the text never refer to those numbers, using the website as reference material hard to use.

I'd suggest numbering the chapter headers according to the book or map or I'd request the feature to map the map clickable by chapter heading. All adventures lack chapter headings for connection to the maps.

**Comment by TheGiddyLimit** [comment]
An unfortunate artifact of the conversion process, I'm afraid. Some of them have been caught and fixed, others haven't. I've added the numbers for that chapter, thanks for alerting me. If you find any other chapters in a similar state, don't hesitate to let me know.

**Comment by Mathizsias** [comment]
A quick scan of the entire HotDQ adventure, they're all missing.

**Comment by TheGiddyLimit** [comment]
Right enough. Went through and added them all, will be live in the next update.
