### ISSUE TITLE
ToB creatures don't have damage vulnerabilities

### ISSUE THREAD

**Issue by MattParsons118** [TheGiddyLimit/TheGiddyLimit.github.io#168]
Damage vulnerabilities are not listed for the following creatures: 
- Beli
- Bone Swarm
- Cactid
- Child of the Briar
- Death Butterfly Swarm
- Greater Death Butterfly Swarm
- Deep One
- Deep One Hybrid Priest
- Deep One Archimandrite
- Apau Perape Demon
- Camazotz, Demon Lord of Bats and Fire
- Mechuiti, Demon Lord of Apes
- Ia'Affrat
- Elder Shadow Drake
- Rust Drake
- Empty Cloak
- Flutterflesh
- Owl Harpy
- Hound of the Night
- Ice Maiden
- Idolic Deity
- Imy-ut Ushabti
- Lindwurm
- Living Wick
- Mask Wight
- Venomous Mummy
- Nightgarm
- Falseman (This one isn't included in the bestiary, but it's just a template rather than an actual creature so I suspect that was intended.)
- Oozasis
- Ostinato
- Ravenala
- Sathaq Worm
- Shroud
- Sharkjaw Skeleton
- Slaugh Swarm
- Theullai (Mispelled as 'Thuellai' in the bestiary)
- Weeping Treant
- Vine Lord
- Tendril Puppet
- Wormhearted Suffragan

**Comment by MrLabRat** [comment]
Fixed!

**Comment by MattParsons118** [comment]
Thanks!
