### ISSUE TITLE
Waterborne Vehicles table mislabeled

### ISSUE THREAD

**Issue by FedoraMark** [TheGiddyLimit/TheGiddyLimit.github.io#181]
**Issue**
The header for the Waterborne Vehicles table is mislabeled in Quick Reference and Player's Handbook. The column labeled WEIGHT should be SPEED.

**Page(s) affected**
- Player's Handbook > Ch. 5: Equipment > 'Mounts and Vehicles' > Waterborne Vehicles (table)
- Quick Reference > Equipment > Mounts and Vehicles > Waterborne Vehicles (table)

**Comment by TheGiddyLimit** [comment]
Fixed, thanks.
