### ISSUE TITLE
TftYP: The Sunless Citadel table of contents partly missing

### ISSUE THREAD

**Issue by FedoraMark** [TheGiddyLimit/TheGiddyLimit.github.io#183]
Is this a bug or a feature request:
Bug

Issue:
The table of contents links for "Tales from the Yawning Portal: The Sunless Citadel" - "Locations on the Grove Level" is largely missing. Although the content exists, the only ToC link is for "Aftermath"

Page(s) affected:
Adventures > 'Tales from the Yawning Portal: The Sunless Citadel' > ''Locations on the Grove Level'' > (Table of Contents bar)

**Comment by TheGiddyLimit** [comment]
👍 fixed for the next release.
