### ISSUE TITLE
Offline Version doesn't work 1.49.13

### ISSUE THREAD

**Issue by JulianWellpit** [TheGiddyLimit/TheGiddyLimit.github.io#184]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: bug report

Issue: The pages don't load unless online

Page(s) affected: All

Reproduction steps: download offline version, deactivate internet, enter offline

Additional information: if accessed while online, the pages also become available offline. The ones that weren't accessed at least once still don't load.

Browser (Chromium, Firefox, Edge, etc): Firefox

Platform (Windows, iOS, Android, etc): Windows 8.1 x64

EDIT: Copied the developement files over the normal  files and now it works

**Comment by TheGiddyLimit** [comment]
This is when downloading from the first link on get.5e.tools, correct (`5eTools.1.49.13.zip`)?

**Comment by TheGiddyLimit** [comment]
Yeahhhh... as suspected, the production files (complete with reliance on external CDN for data) are being used as the download. It's an administrative balls up more than anything else. Hopefully resolved soon!
