### ISSUE TITLE
Selûne and Gaerdal Ironhand are missing the reprinted flag.

### ISSUE THREAD

**Issue by darodrigues** [TheGiddyLimit/TheGiddyLimit.github.io#186]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Bug

Issue: SCAG's Gaerdal Ironhand and PHB's Selûne are missing the '"reprinted": true,' field.

Page(s) affected: Deities.html

Reproduction steps: Reset the filters. No other god from the PHB's "Forgotten Realms" pantheon or the SCAG's "Gnomish" pantheon show up. 

Additional information:

Browser (Chromium, Firefox, Edge, etc):

Platform (Windows, iOS, Android, etc):

**Comment by TheGiddyLimit** [comment]
Fixed in the next release, thanks.
