### ISSUE TITLE
TftYP: The Sunless Citadel - various typos and missing links

### ISSUE THREAD

**Issue by FedoraMark** [TheGiddyLimit/TheGiddyLimit.github.io#188]
Issue:
Various typos and unlinked items in adventure.html for The Sunless Citadel (TftYP)

Page(s) affected:
Tales from the Yawning Portal: The Sunless Citadel > Sunless Citadel Overview > ...
- **Typo:** “10-footdeep” – 3. Crumbled Courtyard > Hidden Pit
- **Typo:** “amd" should be “and” – 12. Tomb of a Failed Dragonpriest > Treasure
- **Unlinked Item:** Quaal’s feather token (tree) – 21. Dragon Throne > Treasure
- **Unlinked Item:** potion of resistance (fire) — 27. Sanctuary > Treasure
- **Unlinked Creature:** diseased giant rat / Guthash — 30. Mama Rat > Creatures
- **Typo:** “goblin s” (goblin is a link) – 33. Practice Range > Creatures

Tales from the Yawning Portal: The Sunless Citadel > Locations on the Grove Level > ...
- **Unlinked:** “goblin commoner” — 47. Belak’s Laboratory > Southwest Chamber
- **Unlinked (x4):** all four 1st level spells are unlinked — 56. The Gulthias Tree > Creatures

Also, interestingly, this is a typo but it exists in the physical book, not sure if you want to change it or not:
- First sentence has a lone “)” character [_"…though no one knows why) sells a…"_] — Preface > The Sunless Citadel > Adventure Hooks > Solving a Mystery

And a few of the adventure specific monsters/npcs have unique bestiary entries, but are unlinked in their introduction sentences: Durnn, Grenl, Erky Timbers, Belak the Outcast,

**Comment by TheGiddyLimit** [comment]
Great stuff as always, will be fixed in the next release.
