### ISSUE TITLE
Suggestion: Xanathar's Guide to Everything's traps to Traps & Hazards page?

### ISSUE THREAD

**Issue by FedoraMark** [TheGiddyLimit/TheGiddyLimit.github.io#189]
_Is this a bug or a feature request:_
Feature Request

_Issue:_
XGE has several example simple and complex traps starting on page 114. Perhaps they'd make a good addition to the Traps & Hazards list?

_Page(s) affected:_
trapshazards.html

**Comment by TheGiddyLimit** [comment]
Funnily enough, it's at the top of my "minor things to do while too dead to do anything more challenging" list, so soon:tm:.
