### ISSUE TITLE
Goliath race has two sources

### ISSUE THREAD

**Issue by FedoraMark** [TheGiddyLimit/TheGiddyLimit.github.io#191]
Is this a bug or a feature request:
Feature request

Issue:
The **goliath** race information can be found in both Elemental Evil Player's Companion and Volo's Guide to Monsters but is only listed as EEPC. I think they're identical, but it seems like VGM should at least be noted; for instance anyone looking at this info for the Adventurer's League's PHB+1 book rule would benefit.

And if added, the race should also be listed in the VGM's book Race list page as well

Page(s) affected:
races.html
book.html#VGM

**Comment by TheGiddyLimit** [comment]
Fair point. There's a few others like this, I'll go through and clean them up soon:tm:
