### ISSUE TITLE
Trinket Table roll result

### ISSUE THREAD

**Issue by FedoraMark** [TheGiddyLimit/TheGiddyLimit.github.io#193]
_Is this a bug or a feature request:_
Bug

_Issue:_
The way the Trinkets table is set up the 1d100 roll result has issues. Instead of two columns the table is set up as 1 column with two trinkets' descriptions and numbers.
**On 1-50)** It'll take the full row of text which includes. <roll result> (#) description A | #+50 | description B
**On 51-100)** undefined result

_**Examples:**_
Trinkets: 12 (12) A small cloth doll skewered with needles | 62 | A silver skull the size of a coin
Trinkets: 51 (51) undefined

_Page(s) affected:_
books.html > Player's Handbook > Ch. 5: Equipment > Trinkets

_Reproduction steps:_
Click the 1d100 link text to auto roll on the table. Do until you get a value from 1-50, then 51-100

**Comment by TheGiddyLimit** [comment]
Will fix.
