### ISSUE TITLE
3 party bestiary missing

### ISSUE THREAD

**Issue by JulianWellpit** [TheGiddyLimit/TheGiddyLimit.github.io#198]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: I think feature

Issue: the entries for the third party monsters ( ex: The Tome of Beasts) are missing

Page(s) affected: Bestiary

Reproduction steps:

Additional information:

Browser (Chromium, Firefox, Edge, etc): Firefox

Platform (Windows, iOS, Android, etc): Windows 8.1

**Comment by JulianWellpit** [comment]
Found them in the Homebrew section. Didn't know you have to download them now.

**Comment by TheGiddyLimit** [comment]
Yep. It was (along with every other update) announced in the Discord, a link to which is in the README; if you're ever wanting to know why something's changed/down, check there first.
