### ISSUE TITLE
unicode character not displaying in dropdown menu

### ISSUE THREAD

**Issue by FedoraMark** [TheGiddyLimit/TheGiddyLimit.github.io#200]
Is this a bug or a feature request:
Bug

Issue:
Looks like the unicode character for `\u2014` doesn't show up in dropdown menus

Page(s) affected:
(at least) lifegen.html

Reproduction steps:
Look at AGE dropdown

Browser (Chromium, Firefox, Edge, etc):
Chrome, Safari

Platform (Windows, iOS, Android, etc):
MacOS (Mojave developer beta)

**Comment by TheGiddyLimit** [comment]
Whoops, got a bit carried away with the bulk character replacement. Fixed next release.
