### ISSUE TITLE
Adventurers League minor issues

### ISSUE THREAD

**Issue by FedoraMark** [TheGiddyLimit/TheGiddyLimit.github.io#201]
In my ongoing quest to apparently look at everything in this project :) ...

Is this a bug or a feature request:
Bug

Issue:
1) Technically the title/menu link should be **Adventurers League** without the apostrophe
2) Typo: Step 4: Describe your Character > Deities – "Step 1& 2" needs a space after the 1
3) External Link: D&D Adventurers League Links > Wiki – link seems to go to an invalid page

Page(s) affected:
book.html#al

**Comment by TheGiddyLimit** [comment]
Yep, yep, and yep. Funny, that last one's in the official PDF. Guess they killed their wiki.
