### ISSUE TITLE
A few more Adventurers League typos

### ISSUE THREAD

**Issue by FedoraMark** [TheGiddyLimit/TheGiddyLimit.github.io#202]
Is this a bug or a feature request:
Bug

Issue:
- "If you want r character...": "r" should be "your" — Adventurers League Player's Guide > Downtime and Lifestyle
- "...deduct 10 days from r downtime total.": "r" should be "your" — Adventurers League Player's Guide > Downtime and Lifestyle > Recording Downtime
- Also, related to the typo from #201 , the comma after "2" doesn't look like it should be there: "listed in Step 1& 2, above are available"

Page(s) affected:
book.html#al

**Comment by TheGiddyLimit** [comment]
Done and done, thanks again.
