### ISSUE TITLE
Winter Eladrin missing reaction

### ISSUE THREAD

**Issue by Saiya-82** [TheGiddyLimit/TheGiddyLimit.github.io#204]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request:

Issue: Winter Eladrin does not have its reaction in its bestiary entry (frigid rebuke) (MTF p197)

Page(s) affected: Bestiary

Reproduction steps:

Additional information:

Browser (Chromium, Firefox, Edge, etc): Chrome

Platform (Windows, iOS, Android, etc): Win 10

**Comment by TheGiddyLimit** [comment]
So it is, tyvm.
