### ISSUE TITLE
Adventurers League v8.0 document

### ISSUE THREAD

**Issue by FedoraMark** [TheGiddyLimit/TheGiddyLimit.github.io#207]
EDIT: v8.1 PG: https://media.wizards.com/2018/dnd/downloads/ALPGv81.pdf

Updated AL document is out (v8.0) and should probably be updated in due time: https://media.wizards.com/2018/dnd/downloads/ALPGv80.pdf

Effective Aug 30th, so no rush I guess :)

( Article page: http://dnd.wizards.com/articles/news/changes-dd-adventurers-league-rewards )

Edit: fixed link to Player’s Guide instead of FAQ

**Comment by TheGiddyLimit** [comment]
I'll put it in my diary.

**Comment by FedoraMark** [comment]
v8.2 documents released: https://www.dmsguild.com/product/208178/DD-Adventurers-League-Player--DM-Pack

**Comment by TheGiddyLimit** [comment]
Since the intent of hosting AL content was to make the Faction Guide available, I've stripped out everything besides that. The "living document" nature makes thing too painful to keep current, otherwise.
