### ISSUE TITLE
Bug: Incorrect Sorting in Adventures.html

### ISSUE THREAD

**Issue by JeffreyStocker** [TheGiddyLimit/TheGiddyLimit.github.io#218]
Is this a bug or a feature request: Bug

Issue: 

Chrome: 
When selecting the sort buttons/headers (on the table) with the id "filtertools",
"Adventure", "levels", and "Published" only change 3 of the books. 
"Name" works correctly. 

Firefox: 
Storyline, levels and published don't sort at all, 
"Name" header works correctly

Page(s) affected: Adventure.html

**Comment by JeffreyStocker** [comment]
Also note, the console give a notice "TypeError: $this.list is undefined[Learn More]"

**Comment by TheGiddyLimit** [comment]
Fixed in next release.
