### ISSUE TITLE
Typo in Spell Point Rules Variant

### ISSUE THREAD

**Issue by BlivetWidget** [TheGiddyLimit/TheGiddyLimit.github.io#222]
Under the variant spell point rules ([https://5etools.com/variantrules.html#spell%20points_dmg](https://5etools.com/variantrules.html#spell%20points_dmg)), unless there's errata I missed, the point cost for a 6th level spell should be 9 (not 8).

**Comment by TheGiddyLimit** [comment]
Good catch. Fixed for next release.

**Comment by BlivetWidget** [comment]
Just happened to be looking in the right place at the right time.  Happy to help.
