### ISSUE TITLE
Stat Block: Hellenrae

### ISSUE THREAD

**Issue by Saiya-82** [TheGiddyLimit/TheGiddyLimit.github.io#225]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Error in a stat block

Issue: Hellenrae from Princes of the Apocalypse shoulf have a speed of 50, not 30.

Hope this helps!  Cheers

**Comment by TheGiddyLimit** [comment]
Fixed for next release; thanks.
