### ISSUE TITLE
Paladin Multiclass Proficiencies Incorrect on Class Page

### ISSUE THREAD

**Issue by MathewBissonnette** [TheGiddyLimit/TheGiddyLimit.github.io#226]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request:
Bug

Issue:
The sidebar description for what proficiencies a character gets when multiclassing into Paladin lists heavy armor, but the PHB only grants up to medium armor.

Page(s) affected:
https://5etools.com/classes.html#paladin_phb

**Comment by TheGiddyLimit** [comment]
True enough. Fixed for next update; thanks.
