### ISSUE TITLE
General Search Bar Navigation with Keys not Working

### ISSUE THREAD

**Issue by MrVizious** [TheGiddyLimit/TheGiddyLimit.github.io#229]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Bug.

Issue: After writing something on the general search bar, you can't navigate through the already written text with the directional keys.

Page(s) affected: All, as far as I am aware.

Reproduction steps: Write something in the search bar and try to press left or right.

Additional information:

Browser (Chromium, Firefox, Edge, etc): Chrome.

Platform (Windows, iOS, Android, etc): Windows 10.

Thank you very much for your work!

**Comment by TheGiddyLimit** [comment]
They instead change the results page, although I agree this isn't very useful. Have removed that functionality for next release (hitting the down arrow to navigate through the results still then allows left/right to be used to switch result pages).
