### ISSUE TITLE
Could the Survival Mantel from Volo's be added?

### ISSUE THREAD

**Issue by Konahrik13** [TheGiddyLimit/TheGiddyLimit.github.io#23]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Feature request

Issue: The other items from the Mindflayer section in Volo's have been added to 5etools but the Survival Mantel hasn't been, likely because it doesn't list stats the usual way. It is pretty easy to "fix" though considering all it says about it is "equivalent to a suit of nonmagical half plate armor". So my thought is just give it half plate stats and then add the details of it after.

Page(s) affected:

Reproduction steps:

Additional information:

Browser (Chromium, Firefox, Edge, etc): Firefox

Platform (Windows, iOS, Android, etc): Windows

**Comment by TheGiddyLimit** [comment]
👌
