### ISSUE TITLE
Bestiary: Black Viper (WDH), rapier damage

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#230]
In the stat block it says his rapier attack does 7 (**1d6**+4) piercing damage.
But a rapier does **1d8** damage. I don't have the adventure so I don't know
if this was a mistake also in the original.

**Comment by TheGiddyLimit** [comment]
It's actually correct according to the book/D&D Beyond :thinking:

Will fix it regardless; it's presumably a mistake.
