### ISSUE TITLE
Bestiary, Animated Object HUGE, constitution

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#231]
The statblock of Animated Object (Huge) has constitution 6 (-2), but all animated objects have constitution 10 (0) regardless of their size. Probably just a slip.
See the spell description for confirmation.

I'm sure you are already aware (and maybe you already did the work, sorry if that's the case)
but recently the updated version of errata to PH, MM, and DMG were released.

**Comment by Temp345** [comment]
Maybe it would be useful to include in the statblock of the animated objects the following info
(taken from the spell description), as a trait perhaps. 

> When the animated object drops to 0 hit points, it reverts to its original object form, and any remaining damage carries over to its original object form.

**Comment by TheGiddyLimit** [comment]
Looks like all their Charisma scores are wrong, too. Both fixed for next release. Good shout on the extra text, have added that too.

The errata should all be in the site (aside from the Demilich Hit Dice change, which we're choosing to ignore since it's incorrect).
