### ISSUE TITLE
Missing Errata update: Beastmaster Ranger, Exceptional Training

### ISSUE THREAD

**Issue by Saiya-82** [TheGiddyLimit/TheGiddyLimit.github.io#232]
Is this a bug or a feature request: missing details on page

Issue: Missing Errata update: Beastmaster Ranger, Exceptional Training

Page(s) affected: Class/Ranger/Beastmaster

[New] Exceptional Training (p. 93).
“Dodge,” has been deleted. Another sentence has been added: “In addition, the beast’s attacks now count as magical for the purpose of overcoming resistance and immunity to nonmagical attacks and
damage.”

Great work on the site BTW!

**Comment by TheGiddyLimit** [comment]
Added it to Spell-less and not the original, woops. Fixed for next release.
