### ISSUE TITLE
Initiative and combat tracker

### ISSUE THREAD

**Issue by eScribMac** [TheGiddyLimit/TheGiddyLimit.github.io#233]
Feature request

It seems like it would be useful to have a page where DM's can track the initiative order in combat, and also show the AC and HP of each participant. Monsters could be pulled in from the bestiary.

I could see about doing a PR for this, if there's any interest.

**Comment by TheGiddyLimit** [comment]
There is; it's part of the DM screen. No AC column, but one can hover statblock names to see the entire statblock.
