### ISSUE TITLE
Add a way to display metric units

### ISSUE THREAD

**Issue by AntoineTA** [TheGiddyLimit/TheGiddyLimit.github.io#238]
**Feature Request**

Hi,

Currently, 5etools is only showing imperial units (feet, miles, pounds, etc.). A setting allowing the user to switch between imperial and metric units (at least in stats blocks for spells and monsters) would be a welcome addition. I do not know if it is even remotely possible in the current state of the project, though.

Just in case, in the various translations of the game, the units are converted as follows:

- 1 ft = 0.3 m
- 1 in = 2.50 cm
- 1 mile = 1.5 km
- 1 pound = 0.5 kg
- 1 gallon = 4 l

Thank you.

**Comment by AntoineTA** [comment]
Thank you for your answer. I just added my vote !

The translated units are indeed the standard for the French localisation of the game (and, I think, other localisations too). You can find more info in [this reddit thread](https://www.reddit.com/r/dndnext/comments/6gkuec/do_the_dd_5e_localised_products_use_the_metric/).

Unfortunately, I only have the books in English, so I cannot provide a screenshot. I do not think the conversion factor is explicitly stated in the text, but the units are consistently used that way.

I also know that Fahrenheit is converted into Celsius, but I do not know which formula (if any) they used. I can do some digging if needed.

**Comment by randomstuff** [comment]
For tactical distances (speed, range of weapons and spells), the conversion used is : 5ft ↔ 1.5m.

**Comment by TheGiddyLimit** [comment]
(Closing as this is tracked in Discord)
