### ISSUE TITLE
This Is Your Life - Life Events Random Numbers are Static After Being Generated

### ISSUE THREAD

**Issue by LivinBreezy** [TheGiddyLimit/TheGiddyLimit.github.io#239]
**Is this a bug or a feature request:** Bug

**Issue:** On the "This Is Your Life" page, when you generate a life, the optional rolls (in italics) become static and don't change per category after they are initially generated. Additionally, the rolls themselves seem to be locked into the option type. For example, the life event "_You spent time working in a job related to your background. Start the game with an extra 2d6 (X) gp._" can appear multiple times. The value of X will stay the same until the page is completely refreshed. Clicking the Generate or Reroll buttons does not reset the value of X. This occurs once for every optional roll type made. For example, if the job-related event appears with its X1 value, the "made an enemy" event can also appear with its own X2 value, which is then static for every instance of the "made an enemy" event. 

I've included some example images of the page, where the first image is generated from a full refresh and the second image is generated by hitting the Reroll button.

![lifegen1](https://user-images.githubusercontent.com/4495369/50745032-52cc5900-11fe-11e9-9e98-3ce6d0e9e513.png)
![lifegen2](https://user-images.githubusercontent.com/4495369/50745033-52cc5900-11fe-11e9-9288-1ba8e0b45f82.png)

**Page(s) affected:** This Is Your Life (lifegen.html). This occurs in both the local version and the main hosted version of the site.

**Reproduction steps:** To generate my results, I was using the following dropdown values from left to right: Elf, +2, Random, Rogue, 61 Years or Older. Once I put those in, I hit Generate and then click Reroll on the Live Events section. I also have Night Mode on, if that could make a difference.

**Additional information:** None.

**Browser (Chromium, Firefox, Edge, etc):** Chrome and Firefox produce the same result.

**Platform (Windows, iOS, Android, etc):** Windows 10 Education.

**Comment by TheGiddyLimit** [comment]
Good catch. Fixed for next release.
