### ISSUE TITLE
Adding a poison filter to the Items section?

### ISSUE THREAD

**Issue by Konahrik13** [TheGiddyLimit/TheGiddyLimit.github.io#24]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Request

Issue: They are listed in Adventuring Gear so technically they're in the right spot. I just think of adding a poison section could make it easier to find them. Not a big deal if not accepted though since, again, they're already where they are.

Page(s) affected: Items

Reproduction steps:

Additional information:

Browser (Chromium, Firefox, Edge, etc):

Platform (Windows, iOS, Android, etc):

**Comment by TheGiddyLimit** [comment]
Good call; added.
