### ISSUE TITLE
This Is Your Life - Romantic Partner Died Does Not Generate Result

### ISSUE THREAD

**Issue by LivinBreezy** [TheGiddyLimit/TheGiddyLimit.github.io#240]
**Is this a bug or a feature request:** Bug

**Issue:** On the "This Is Your Life" page, when you generate a life, the Life Event "_Tragedy: A current or prospective romantic partner of yours died._" does not generate a result, regardless of whether or not you have previously generated a Spouse. It simply shows up as an undefined result. 

I've included some example images of the broken event:

![lifegen3](https://user-images.githubusercontent.com/4495369/50745427-74c6db00-1200-11e9-85a1-a18be1188b45.png)
![lifegen4](https://user-images.githubusercontent.com/4495369/50745428-74c6db00-1200-11e9-9483-64d26be8b092.png)

**Page(s) affected:** This Is Your Life (lifegen.html). This occurs in both the local version and the main hosted version of the site.

**Reproduction steps:** To generate my results, I was using the following dropdown values from left to right: Elf, +2, Random, Rogue, 61 Years or Older. Once I put those in, I hit Generate and then click Reroll on the Live Events section. I also have Night Mode on, if that could make a difference.

**Additional information:** I'm not sure if something is supposed to be produced as a result or not (since the table in Xanathar's Guide is open-ended), but it may also be a place to produce an optional d12 die roll to determine who was responsible for your partner's death.

**Browser (Chromium, Firefox, Edge, etc):** Chrome and Firefox produce the same result.

**Platform (Windows, iOS, Android, etc):** Windows 10 Education.

**Comment by TheGiddyLimit** [comment]
...and same for this. Cheers!
