### ISSUE TITLE
Encounter builder XP calculation broken

### ISSUE THREAD

**Issue by MathewBissonnette** [TheGiddyLimit/TheGiddyLimit.github.io#241]
Is this a bug or a feature request: 
Bug

Issue: 
Bestiary no longer correctly displays encounter XP

Page(s) affected: 
bestiary.html

Reproduction steps: 
1. Add monster to encounter via + button in statblock
2. Look at the Total and Encounter XP displayed

Additional information:
For example, Cyclops adds as a 25,300 XP monster with an encounter XP of 75,900.

Browser (Chromium, Firefox, Edge, etc):
Chrome and Firefox

Platform (Windows, iOS, Android, etc):
Windows

![image](https://user-images.githubusercontent.com/24984298/51585291-a80a9a80-1e8d-11e9-85b8-6836a9ce32ba.png)

**Comment by TheGiddyLimit** [comment]
:+1: Fixed, will hopefully deploy it tonight (in ~5 hours).
