### ISSUE TITLE
Commit d916e88e28d24520d249b499fc9be48b630c8f28 break IOS compatibility for bestiary

### ISSUE THREAD

**Issue by thaihugo** [TheGiddyLimit/TheGiddyLimit.github.io#243]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Bug

Issue: commit d916e88e28d24520d249b499fc9be48b630c8f28 breaks the bestiary webpage. It never loads and stays in a “Loading” stage on safari IOS 11. It is working normally on previous commit. Loading the page brings all monsters and displays the first monster in the list

Page(s) affected: bestiary.html

Reproduction steps:
On local web server lighttpd on Debian.
Git checkout d916e88e28d24520d249b499fc9be48b630c8f28
Clear web cached data on safari
Load bestiary webpage on Safari, stays on “Loading”
Git checkout 09058709ac09a08e074a9aae81957102f349eb77
Clear web cached data on safari
Load bestiary webpage on Safari, Display monster list and first monster

Additional information:
I know safari is not on the support list, but it was working perfectly before this version. If the change are not critical for development, it would be nice to adapt them for keeping compatibility.

Thanks

Browser (Chromium, Firefox, Edge, etc):
Safari

Platform (Windows, iOS, Android, etc):
iOS 11.3

**Comment by TheGiddyLimit** [comment]
That commit is really ~90 commits in one, a tad tricky to pinpoint the issue without some logs; would you be able to provide any browser console output? 

It seems to work in iOS 12, and I don't have access to anything older.

**Comment by thaihugo** [comment]
Ok, I don’t have a Mac so I’ll be limited in terms of debugging, but I have some tools on my IPad and I’ll try to give you as much info as I can.
It seems to get stuck after target-min-script.js 
![00e13cec-0442-43db-bf46-7dcfed345007](https://user-images.githubusercontent.com/17780673/51796822-47d07b80-2234-11e9-9fa0-a57269bc76df.jpeg)

**Comment by TheGiddyLimit** [comment]
Hm. Sadly that doesn't give much info; the scripts will wait until everything's loaded before trying to execute anyway. It might just be a bust, I'm afraid. Is iOS 12 not something you can use?

**Comment by thaihugo** [comment]
Not really. I’ll investigate the issue and post if I find the reason.

I can see that Chromium on Linux cannot load 5etools/bestiary.html, so it’s might not be only a problem from IOS

**Comment by thaihugo** [comment]
Here is the debug log on Chromium:
![77a397dd-4a39-41b5-8954-3c00d7bb31ec](https://user-images.githubusercontent.com/17780673/51812458-8b86bc00-22ec-11e9-95fd-c6627515cd10.png)

The trackers are blocked by my DNS. Even if I let them go, it seems the issue is on the last line.

**Comment by TheGiddyLimit** [comment]
Well, so much for "I'll do it tonight."

However, I will _actually_ fix this tonight.
