### ISSUE TITLE
Bestiary and Encounter json cross-compatibility

### ISSUE THREAD

**Issue by MathewBissonnette** [TheGiddyLimit/TheGiddyLimit.github.io#245]
Is this a bug or a feature request:
Feature Request

Issue:
Currently, Bestiary json files and Encounter json files are not interchangeable. To convert a Bestiary list into an encounter I have to load it in the bestiary, then go to encounter builder, then download as an encounter. Similarly, I cannot simply load Bestiary files into the DM Screen Initiative Tracker. It would be nice if the two shared a common format since they are used for essentially the same thing.

**Comment by TheGiddyLimit** [comment]
Added for next release 👍

**Comment by MathewBissonnette** [comment]
Just checked, and encounter.json will upload fine as a bestiary sublist, but the bestiary-sublist.json won't upload as an encounter (bestiary sublist being the thing generated by the pictured button)

![image](https://user-images.githubusercontent.com/24984298/52319408-5c241f00-297e-11e9-9551-f2270e421aab.png)

**Comment by TheGiddyLimit** [comment]
Can't reproduce; both are working for me. Mind sending me the file? Pasting it here is fine, or whatever else suits.

**Comment by MathewBissonnette** [comment]
Hmm. Github won't let me upload a json so I'm just changing the extension to txt.

The bestiary-encounter.json loads fine in the 2 ways to upload it in the Bestiary page (encounterbuilder:false and encounterbuilder:true), but not in the DM Screen Initiative Tracker tool


[bestiary-sublist.txt](https://github.com/TheGiddyLimit/TheGiddyLimit.github.io/files/2846200/bestiary-sublist.txt)

**Comment by TheGiddyLimit** [comment]
Ah, fair enough. Fixed for next release.
