### ISSUE TITLE
Initiative tracker condition hover text broken for first entry on DM side

### ISSUE THREAD

**Issue by MathewBissonnette** [TheGiddyLimit/TheGiddyLimit.github.io#246]
Is this a bug or a feature request:
Bug

Issue:
The conditions added to a creature produce hover text displaying the condition name, but not for the first entry in the list.

Steps to Reproduce:
Add multiple entries to the initiative tracker
Give conditions to the one at the top of the list
Give conditions to someone lower down
Hover mouse over condition indicator

Page(s) affected:
DM Screen Initiative Tracker

Browser (Chromium, Firefox, Edge, etc):
Chrome, Firefox

**Comment by TheGiddyLimit** [comment]
Fixed for next update. Cheers.
