### ISSUE TITLE
Minor typo in table

### ISSUE THREAD

**Issue by BlivetWidget** [TheGiddyLimit/TheGiddyLimit.github.io#247]
Very minor typo, just happened to notice:

Location:
Rules | Tables | DM Screen; NPC Ideals

Is:
4 | Creativity (chatoric)

Should be:
4 | Creativity (chaotic)

Thank you for all of your excellent work!

**Comment by TheGiddyLimit** [comment]
:+1: corrected for next release.

And, thanks! :grin:
