### ISSUE TITLE
Bestiary: Demilich is Missing

### ISSUE THREAD

**Issue by mclemente** [TheGiddyLimit/TheGiddyLimit.github.io#249]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Bug

Issue: Demilich is missing from Bestiary

Page(s) affected: Bestiary

Reproduction steps: Go to Bestiary, search for "demi" or "demilich". There'll be no results. Searching for "lich" gives 4 results that aren't it either.

Additional information: The Demilich already exists in the bestiary-mm.json file (Line 11286) along with an "Acererak Demilich" variant (Line 320)

Browser (Chromium, Firefox, Edge, etc): Firefox/Chrome

Platform (Windows, iOS, Android, etc): Windows

**Comment by MathewBissonnette** [comment]
![image](https://user-images.githubusercontent.com/24984298/52512927-5d428f80-2bbc-11e9-98a2-7f3b1d7b6998.png)
![image](https://user-images.githubusercontent.com/24984298/52512932-65023400-2bbc-11e9-815a-e15d97e7b892.png)

I see it in the results for both

**Comment by TheGiddyLimit** [comment]
Works for me, too. There's a minor bug in the live version of the Bestiary filters, so this might be resolved on next update.

**Comment by mclemente** [comment]
> 
> 
> Works for me, too. There's a minor bug in the live version of the Bestiary filters, so this might be resolved on next update.

Yup, I thought the live version was up to date, so it didn't even cross my mind to check the local files. Sorry.
