### ISSUE TITLE
Bestiary Allip is missing

### ISSUE THREAD

**Issue by VagueDolphin** [TheGiddyLimit/TheGiddyLimit.github.io#250]
Issue: Allip is missing from the bestiary list. It can still be found through other search features, but is not listed

![screenshot_2019-02-12 allip - 5etools](https://user-images.githubusercontent.com/47567661/52646243-0a145980-2ea8-11e9-8f43-419923676657.png)

**Comment by TheGiddyLimit** [comment]
Yep, there's several others that are the same. It's fixed for next release.
