### ISSUE TITLE
Encounter Builder

### ISSUE THREAD

**Issue by tsfstarr** [TheGiddyLimit/TheGiddyLimit.github.io#252]
Is this a bug or a feature request: 
Bug

Issue: 
XP total not updated by reducing number

Page(s) affected: 
https://5etools.com/bestiary.html#ogre_mm,encounterbuilder:true

Reproduction steps: 
Open encounter builder, 
click + symbol to add two monsters, 
click - symbol to reduce monster by one, 
see "Total XP" and "Adjusted XP" values.

Additional information: Tested with a few different kinds of monsters and party sizes.

Browser (Chromium, Firefox, Edge, etc): Chrome 72.0.3626.109 (Official Build) (64-bit)

Platform (Windows, iOS, Android, etc): Windows 7

**Comment by TheGiddyLimit** [comment]
Fixed for next release.
