### ISSUE TITLE
[BUG] Items, Filter, Category: exclude Specific Variant (default setting)

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#254]
The **Specific Variant** filter (Category) don't seem to work as expected when used
to "exclude" (reddish-brown background) which is the default setting.

Example: just put "dragon scale" in the filter textbox in the item page.
All the specific variants are listed instead of just the default one. 

[LINK 1 - (add "dragon scale" in the textbox) - this filter should exclude specific variants of an item but it doesn't ](https://thegiddylimit.github.io/items.html#black%20dragon%20scale%20mail_dmg,filtersource:,filtertype:,filtercategory:)

Additionally, please check the "Dragon scale mail" item which doesn't seem to be tagged/categorized as generic variant.

There might be some problems also with the **Generic Variant** filter.
If you exclude both Generic Variant and Specific Variant, both are listed anyway: specific ones were expected due to the previously mentioned bug, but generic ones are also listed.
Try for example putting "resistance" as text filter: "ring of resistance" is listed alongside "ring of fire resistance".
EDIT: oh, this too seems caused to bad categorization. "Armor of resistance" is correctly filtered out for example. And oddly enought also specific variants of the armor of resistance are filtered out but only because both generic and specific variant filters are excluded.

So... you try figure it out, I'm confused :P

**Comment by TheGiddyLimit** [comment]
It's less a problem with the filters, and more a problem with the item data, it appears. All the rings of resistance are specified as their own item, instead of one generic variant. I'm sure there's some historical reason for that, but I'll see if I can clean it up some.
