### ISSUE TITLE
Tables not loading in Microsoft Edge

### ISSUE THREAD

**Issue by Mist-Hunter** [TheGiddyLimit/TheGiddyLimit.github.io#256]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request:
bug(?)

Issue:
Any tables (right word?) in the site fail to load in Microsoft Edge. 

Page(s) affected:
Bestiary, Items, Classes etc.

Reproduction steps:
Open in Edge

Additional information:
First, thanks for the site! Most amazing RPG info site I've ever seen. I wish all systems had something like this :)

I don't normal use Edge, but on my Surface tablet, I find it to be a decent touch browser. I'm guessing Edge is no longer supported by 5etools, but in case there is a simple oversight, I'm submitting this.

I'd paste some info from Edge's developer config, but I don't know enough about what I'm looking at to be useful.

Browser (Chromium, Firefox, Edge, etc):
Edge

Platform (Windows, iOS, Android, etc):
Windows 10, all devices.

![image](https://user-images.githubusercontent.com/6420684/54438918-f7827f80-46f4-11e9-96e1-e262d477c054.png)

**Comment by TheGiddyLimit** [comment]
I'm afraid we don't support Edge; never have, and never will. It says this on the homepage, iirc.
