### ISSUE TITLE
Render.js _renderImage function problem with internal books on IOS 12

### ISSUE THREAD

**Issue by thaihugo** [TheGiddyLimit/TheGiddyLimit.github.io#259]
Hi,

Since the commit 10 days ago, the images doesn't display on IOS 12 for internal scenario. For homebrew, the display is working normally.

For example, in curse of strahd, no image will be displayed. Clicking on an image displays the image in a new fullscreen tab.

If I add a homebrew, from the standard list, images display normally (for example "siege of castle rend")

I don't know if it's an easy fix. As usual, I'm available for additional debug.

Thanks
![90551D64-4F43-450C-8C01-518B28E60940](https://user-images.githubusercontent.com/17780673/55131459-a85b3680-5159-11e9-9a90-08ae452217bd.jpeg)
![750A3D0C-47AC-4887-95B2-0AF44E8A20F9](https://user-images.githubusercontent.com/17780673/55131460-a85b3680-5159-11e9-8552-34ed72bd5226.jpeg)

**Comment by TheGiddyLimit** [comment]
Hm. Hard to say without seeing console logs, is that something you're able to provide?

**Comment by thaihugo** [comment]
Not really, but I'll try to modify the code on my server to pinpoint the faulty tag and report here. Please give me a few days so I can investigate.

Thanks

**Comment by thaihugo** [comment]
In /js/render.js, in line 295, replacing the img tag src ${svg || href} by a simple ${href} solves the problem:

> textStack[0]` += `<div class="rd__wrp-image"><a href="${href}" target="_blank" rel="noopener" ${entry.title ? `title="${entry.title}"` : ""}><img class="rd__i     mage" src="${href}" ${entry.altText ? `alt="${entry.altText}"` : ""} ${svg ? `data-src="${href}"` : `""}></a></div>`;

Is this sufficient for your diagnostic?

**Comment by TheGiddyLimit** [comment]
Not so much; that's dealing with the symptoms, and not addressing the cause. Reverting to non-dynamic image loading would certainly "fix" the problem, but it's a feature I'm not quite ready to sacrifice.

Could you try saving this as e.g. `test.html` and opening it, and screenshot/provide the output?

```
<!DOCTYPE html>
<head>
	<script>
		window.addEventListener("load", () => {
			const $out = document.querySelector(`#output`);
			$out.innerHTML = `${typeof IntersectionObserver}<br>
			${navigator.appCodeName}<br>
			${navigator.appName}<br>
			${navigator.appVersion}<br>
			${navigator.userAgent}`;
		});
	</script>
</head>
<body>
	<div id="output"></div>
</body>
</html>
```

**Comment by thaihugo** [comment]
Here it is (the "undefined" is the first line of the output):


undefined
Mozilla
Netscape
5.0 (iPad; CPU OS 12_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1
Mozilla/5.0 (iPad; CPU OS 12_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1

**Comment by TheGiddyLimit** [comment]
Perfect, that's what I was hoping for. Fixed for next release :+1:
