### ISSUE TITLE
[Bug] LMoP Adventure, Ruins of Thundertree, Ash Zombies sidebar

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#26]
In the Ruins of Thundertree section there are a few references to _(see the "Ash Zombies" sidebar)_ but there's no such sidebar/paragraph.

> 
> **ASH ZOMBIES**
> These zombies were created by the magical devastation when Mount Hotenow erupted thirty years ago. They use the zombie stat block, with the following additional trait.
> 
> **Ash Puff**. The first time the zombie takes damage, any living creature within 5 feet of the zombie must succeed on a DC 10 Constitution saving throw or gain disadvantage on attack rolls, saving throws, and ability checks for 1 minute. A creature can repeat the saving throw at the end of each of its turns, ending the effect on it early with a successful save.

**Comment by TheGiddyLimit** [comment]
Good catch. The Fantasy Grounds module I'm ripping this from is missing it too; they instead have it attached to the creature, which is then linked. Will fix.
