### ISSUE TITLE
"Roll HP" in initiative tracker doesn't work properly

### ISSUE THREAD

**Issue by antocuni** [TheGiddyLimit/TheGiddyLimit.github.io#261]
Is this a bug or a feature request: bug

Issue: 

  - go to the DM Screen

  - add an Initiative Tracker panel

  - click on the green "Add Monster" button

  - enable the "Roll HP" checkbox

  - add one or more monsters

In this scenario, I'd expect the HP of each monster to be  rolled; however, it's always set to the average value.

Browser (Chromium, Firefox, Edge, etc): Chome and Firefox

Platform (Windows, iOS, Android, etc): Linux (Ubuntu)

**Comment by TheGiddyLimit** [comment]
Confirmed; fixed for next release :+1:

**Comment by antocuni** [comment]
Any rough schedule for when the next release will be?

**Comment by TheGiddyLimit** [comment]
When it's done.
