### ISSUE TITLE
[BUG] Feats, half-feats rendering when hovering

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#263]
My pull request to try to fix the missing of the first bullet point of the Resilient feat
was rightfully dismissed because the problem was not in the data (like I thought)
but in the rendering of the feat while hovering on its name (e.g. in omnisearch).

I added that information in the pull request comment but you may have missed
that (you got no notification because it was already closed, perhaps).
Or maybe you saw that but didn't have time to check it out yet.

So, just to make sure, here I am. Half-feats (feats that also add a +1 to an ability score)
are rendered correctly when you "select them" but not when hovering on them:
they are missing the bullet point about the ability score increase.

How to reproduce: put "resilient" or "athlete" in the omnisearch input field.

Bye!

**Comment by TheGiddyLimit** [comment]
A-ha, right enough. I did see the other comment, but I'll admit I skim-read the email notification, so thanks for posting it as a full issue 😁 

Fixed for next release.
