### ISSUE TITLE
Sage Advice

### ISSUE THREAD

**Issue by tsfstarr** [TheGiddyLimit/TheGiddyLimit.github.io#264]
Is this a bug or a feature request: feature request

Issue: sage advice 

Page(s) affected: rules

Additional information:
Could the sage advise compendium be added to 5etools? At least under optional?

**Comment by TheGiddyLimit** [comment]
No. We try to avoid incorporating "living documents" whenever possible, and Sage Advice is of low enough value that it's not worth the hassle of maintaining a copy. If there are rulings in Sage Advice beyond simply re-stating the original text of an ability with a "RTFM" note attached, we do incorporate those, however (see the note on Elf's "Trance"). If there are any such RAW-changing notes you feel are missing, do point them out, and we'll consider adding them.

I will say, however, that there's nothing stopping someone from converting the PDF and submitting it as Homebrew; I'd happily make that available.

**Comment by tsfstarr** [comment]
Fair what you say; there's no point repeating content.

What made me think about it: 
there is revised wording of the wizard class' Arcane Ward to state its starting points are its maximum.
