### ISSUE TITLE
[BUG] Bestiary, Champion entry sometimes rendered with replaced text from a derived entry

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#266]
Sometimes, not always, the **Champion** entry (both the regular one and that
you get by hovering the mouse pointer to the link) displays "*Sundeth*" instead of
"the champion" in the text of all his traits and actions:
- indomitable 
- second wind
- multiattack
- greataxe  (the part about the extra dmg if hp > half max hp)
- shortbow (the part about the extra dmg if hp > half max hp)

**Sundeth** is a named NPC from WDMM (a **Champion** with a few modifications).

I wasn't able to pinpoint an exact sequence of steps to reproduce this behaviour.
My best guess is that it has somehow to do with rendering the **Sundeth** entry
at least once, because before doing that the **Champion** entry looked fine.

This "mixed entry" doesn't seem to happen on 5etools.com. Nnot that I have tested it too
much there, but by the time I could make it happen and somehow reset it - refreshing the
page multiple times and changing pages - on github a few times,
I could never make it happen on 5etools.com.

By the way, **Sundeth** should display "giant" (being an half-ogre) as type instead of "humanoid (any race)", a leftover of the generic **Champion** NPC. I tested that you
can simply  "overwrite" the original type adding
`			"type": "giant",`
after
`			"size": "L",`
in **Sundeth**'s json entry.

It also displays: "Source: WDMM, page 304. Also found in WDMM."
(the "Also found..." part seems a copy/paste involuntary remnant).
Oh, I see why this is happening, see next paragraph.

I checked the data and noticed that the **Sundeth** entry in bestiary-wdmm.json
is based on the **Champion** from VGM - to not rewrite the same text.
So the problems could be about the rendering: somehow that operation of replacing
"the champion" with "Sundeth" is used also for the original entry, at least for a time?

I wonder why the same thing doesn't happen with "mage" and "kavil".
What's the difference? Could it be that Champion also uses WDMM as other source?

Sorry if this sounded a bit incoherent, I've edited it a dozen times to try to provide
more and better information. Thanks for your hard work.

**Comment by TheGiddyLimit** [comment]
Interesting. That _should_ be impossible, at least from a code perspective. A strict copy with no reference to the original is made always made before the merge. I've never seen it happen, in any case, nor can I seem to reproduce it. If you manage to do so semi-consistently, do let me know.

The `Also found in` duplication is/was indeed a bug, already fixed for next release.

**Comment by Temp345** [comment]
It keeps happening but I can't find any logic/trigger behind it. I'll keep looking.

In the meantime, I have a curiosity if you don't mind. It says that the Champion's
environments are urban and desert (bottom-right of the statblock).
Does that info comes from an official source?

**Comment by TheGiddyLimit** [comment]
Even describing some general usage scenarios might be helpful? I couldn't seem to trigger it, when I tried. I'm guessing something related to loading times; our servers will likely be less responsive than GitHub's CDN.

The environment information is in the back of VGM itself, if I remember correctly. Or D&D Beyond, should you have access there (although the latest printings/PDFs are generally considered gospel; Beyond has some issues).

**Comment by Temp345** [comment]
This is how it happened the last time.

From the [main page](https://thegiddylimit.github.io/5etools.html), I've put "champ" in omnisearch.
I hovered on the link and the info was correct.
The I clicked the link and I get the same entry (title of the monster was Champion
and had "info" and "images" tab correctly assigned) but with "Sundeth" instead of "the champion".

Unfortunately it doesn't always happen like this, but after some attempts ii happens
(hovering might be a constact, not sure).
A refresh with F5 shows the entry correctly (NOT ALWAYS, actually it was a fluke,
it never worked again). CTRL+r doesn't work either.

Changing page seems to temporarily fix the entry displayed when hovering on its link.
I can't find a way to fix the regular display of the entry once it gets "corrupted".

I also tried to blacklist WDMM to see what happen but no dice.

I doubt it matters but this is on Linux using Firefox 66.0.2 (64-bit).

-------

OS: win10 64-bit
Browser: Chromium Version 75.0.3755.0 (Developer Build) (64-bit)

It happens here too.
A CTRL-F5 fixed the regular view but hovering on the link (from omnisearch) still displayed "Sundeth".

I changed page and tried again omnisearch and now hovering showed the right info: "the champion".
So this seems like a constant between the two browsers/OSs.

**Comment by TheGiddyLimit** [comment]
Aha, it's something I'd already fixed/forgotten I'd fixed for next release. Was able to reproduce it following your instructions, cheers for that.

There should be no effective code difference between the main site and this repo (currently, at least), beside some ads being injected. So ultimately, as mentioned, probably a loading time race condition somewhere. No point worrying about it, either way.
