### ISSUE TITLE
Adventures Link

### ISSUE THREAD

**Issue by sparky1088** [TheGiddyLimit/TheGiddyLimit.github.io#267]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Possibly a bug (or an oversight), it might be a feature request/preference for me in particular.

Issue: The only way to get to the list of adventures is to go to an adventure and then click on the link from that page. It would be nice if the nav menu linked to either adventures.html

Page(s) affected: Technically any that use the nav menu (so all)

Reproduction steps: choose the dropdown under dm tools and adventures only brings out the list 

Additional information:

Browser (Chromium, Firefox, Edge, etc): All

Platform (Windows, iOS, Android, etc): Currently on linux but it would be the same on all systems

**Comment by TheGiddyLimit** [comment]
There's a link to it at the bottom of that nav list.

**Comment by sparky1088** [comment]
I missed that, thanks!
