### ISSUE TITLE
Filenames contain special characters not compatable with FAT filesystems.

### ISSUE THREAD

**Issue by doerrie** [TheGiddyLimit/TheGiddyLimit.github.io#269]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Bug

Issue:

Files contain names that are not FAT32-compatable.  This creates problems for thumb-drives and Android devices.  Please consider URL-encoding file names before releasing them or avoiding special characters in filenames altogether.

Page(s) affected:

Example:
https://github.com/TheGiddyLimit/TheGiddyLimit.github.io/blob/master/img/PotA/Ogr%C3%A9moch.png

The diacritic character "%C3%A9" is not supported in FAT 32

Reproduction steps:

Unzip current distribution to a FAT filesystem.

Additional information:

Browser (Chromium, Firefox, Edge, etc): FAT 32 Filesystem

Platform (Windows, iOS, Android, etc): Android 5

**Comment by TheGiddyLimit** [comment]
Fair enough. Fixed for next release.

**Comment by doerrie** [comment]
Thanks! 😄
