### ISSUE TITLE
[Bug] Adventures, SKT, broken links

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#27]
Many of the links in the left sidebar are now working properly.

Introduction

- 	creating new giant lords
- 	factions of the north
- 	deadly encounters

Ch. 1

- 	Nightstone: General features
- 	The Nandars of Nightstone
- 	Dripping Caves: General features

Ch. 3

-   Forgotten forest (maybe because of that "...")
- 	High Forest (...)
- 	IcePeak (maybe should be Ice Peak)
- 	Icewind Dale
- 	Iron Master (maybe should be Ironmaster)
- 	Iymrith's Lair
- 	Mirabar (points to Mines of Mirabar)
- 	Mithral Hall
- 	Moonwood
- 	Nesme
- 	orthfurrow (works, but should be Northfurrow)
- 	Sea of Moving Ice
- 	Star metal Hills (Starmetal Hills?)
- 	Tuem (Tuern?)
- 	Vordrorn Forest (...)

Ch. 4

- 	Eye of the All-Father: General Features
- 	Hekaton's Conchs
- 	Encounter with Iymrith

Ch. 7

- 	Svardog (points to Reclaiming Svardborg, which is part of the Frost Giant section)

Ch. 8

- 	slaves of the yakfolk

Ch. 12

- 	Harshnag Returns!

**Comment by TheGiddyLimit** [comment]
You're a god. Fixed.

Changed the way the linking works, so it requires an exact match now (instead of e.g. `orthwood`). Since it's stricter now, some other's might've broken. I hope you have a nice way of checking these you could send over, and didn't go through them by hand...?

**Comment by Temp345** [comment]
By hand. Maybe a link checker can help?

Thanks for all your hard work.

**Comment by TheGiddyLimit** [comment]
Wew, that sounds intensely boring. Your dedication will be remembered.

I'll perhaps write a checker script once I get done adding TftYP and ToA. Might be a while with them, though, there's some interesting challenges involved that didn't exist in the older content 😞
