### ISSUE TITLE
Polymorph Blade rarity

### ISSUE THREAD

**Issue by SigmaRaven** [TheGiddyLimit/TheGiddyLimit.github.io#270]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Bug

Issue: Rarity listed as Rare instead of Very Rare

Page(s) affected: Polymorph Blade (generic variant)

Reproduction steps: References -> Items -> Polymorph Blade, displayed rarity is 'Rare'

Additional information:

Browser (Chromium, Firefox, Edge, etc):

Platform (Windows, iOS, Android, etc):

**Comment by TheGiddyLimit** [comment]
Cheers; fixed for next release.
