### ISSUE TITLE
Point buy calculator seems to be broken

### ISSUE THREAD

**Issue by kieranpenriceaiglobal** [TheGiddyLimit/TheGiddyLimit.github.io#271]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request:
Bug

Issue:
The point buy system seems to no longer be updating the remaining points when the stats are changed. Checked on desktop and mobile. Previously worked fine? Looked in inspect element and not getting any JS errors.

Page(s) affected:
Point buy calculator

Reproduction steps:
Add the stats, reduce the stats. Total remaining points does not change.

Additional information:

Browser (Chromium, Firefox, Edge, etc):
Chrome (desktop and mobile). Also tested in opera, firefox and edge on desktop. Same result, except for edge where the page doesn't even appear?

Platform (Windows, iOS, Android, etc):
Windows 10. Latest version. Android 8.

**Comment by TheGiddyLimit** [comment]
Works fine here, you're adjusting the stats in the "base" column, yes?

If you've configured it with custom rules, please export them as either a file or a URL and post it here.

**Comment by kieranpenriceaiglobal** [comment]
Oh so you adjust it via the base? So what is user for? I thought it used to be that you did it via user?

Either way, it's not a bug I guess! I'll close the bug report.

Thanks for the quick reply and keep up the good work, this thing really is totally awesome and has made running my games SO much easier. Thank you for it!

**Comment by TheGiddyLimit** [comment]
No worries, and thanks!

The "User" column has a tooltip explaining its use; it's for other things you might want to add in as a player.
