### ISSUE TITLE
Plate Armor Removed

### ISSUE THREAD

**Issue by noobapprentice69** [TheGiddyLimit/TheGiddyLimit.github.io#272]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Possibly bug

Issue: Plate armor, as it is in D&D, is no longer in the Items list, no matter how the filters are arranged.

Page(s) affected: Items

Reproduction steps: Go into the Items list under References and search "plate armor." Regular plate armor (mundane, as it should be under) isn't there.

Additional information: N/A

Browser (Chromium, Firefox, Edge, etc): Chrome

Platform (Windows, iOS, Android, etc): Chrombook
![Screenshot 2019-05-20 at 8 43 23 PM](https://user-images.githubusercontent.com/50851674/58060574-f54b0000-7b3f-11e9-8359-e2bb1ad5c8d6.png)

**Comment by TheGiddyLimit** [comment]
Bugged indeed. Fixed on the main site soon.
