### ISSUE TITLE
[SUGGESTION] MM Bestiary Fluff, addendum to Mind Flayer Arcanist

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#274]
How about adding that short line in the Variant sidebar (MM pag 222)
to the info tab of the Mind Flayer Arcanist?

File was too big to edit with the browser editor, but here's the change needed
in **data/bestiary/fluff-bestiary-mm.json**. Tried in my local copy and it seems to work fine.

```
		{
			"name": "Mind Flayer Arcanist",
			"source": "MM",
			"entries": [
				"A few mind flayers supplement their psionic power with arcane spells. However, they are regarded as deviants by their illithid peers and usually shunned."
			],
			"_appendCopy": {
				"name": "Mind Flayer",
				"source": "MM"
			}
		},
```

**Comment by TheGiddyLimit** [comment]
Can do 👍

**Comment by Temp345** [comment]
Just realized the same thing can be done for the Mind Flayer Psion (VGM pag 71):

_Mind flayers sometimes devote themselves to deeper
study of psionic power, and many excel at using their
innate psionic energy to duplicate the casting of spells._
