### ISSUE TITLE
Import from GMBINDER: Pokemon 5e

### ISSUE THREAD

**Issue by Offki** [TheGiddyLimit/TheGiddyLimit.github.io#275]
https://pastebin.com/8XUhTWuV

**Comment by TheGiddyLimit** [comment]
This is... extremely unhelpful. What are you expecting me to do, exactly?

**Comment by Offki** [comment]
My bad. It was a "request" to have the homebrew included in the repository(?). On the discord it says to make a new issue and place the link. What is the proper procedure?

**Comment by TheGiddyLimit** [comment]
Ah, I see. Well first off, the homebrew repo is [over here](https://github.com/TheGiddyLimit/homebrew). Secondly, creating an issue with a dump is for when you've converted the homebrew to 5etools' format. If you want someone else to do the conversion, you're best off asking on the Discord. Generally, though, if you want it converted, you have to do it yourself.
