### ISSUE TITLE
Missing Dragon of Icespire Peak images on Github

### ISSUE THREAD

**Issue by thaihugo** [TheGiddyLimit/TheGiddyLimit.github.io#277]
Hello,

Just a quick head up to signal the Dragon of Icespire Peak have not been properly transfered on the Gihub Repo. 

Thanks for your work

Thaihugo

**Comment by TheGiddyLimit** [comment]
So they are. Strange; the tool I used to commit the files completely missed them. Have done it all by hand now, should be fixed.
