### ISSUE TITLE
[BUG?] Bestiary, Yeenoghu (both OotA and MTOF), constitution ability score and modifier

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#283]
I don't have MTF, but in OotA Yeenoghu's constitution modifier is 8 instead of 6
(note that in OotA his score is 23 which should give a +6 modifier, but it should be
26 or 27, who knows, maybe someone can check if it's been fixed on DnD Beyond?).

See also his HP (the constitution bonus part) and his constitution saving throw
 (15 total - 7 proficiency = + 8 con Mod)

Bye!

**Comment by TheGiddyLimit** [comment]
Seems he's been cleaned up indeed. Should be 26. Fixed for next release.
