### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by AblingerOscar** [TheGiddyLimit/TheGiddyLimit.github.io#284]
Issue: When searching for anything, the preview will be correct, but the link is broken (Tested with items and conditions)

Page(s) affected: Search function on 5e.tools/items/item-name.html

Reproduction steps: Go to any [items html page](https://5e.tools/items/staff-of-power-dmg.html) and search for any item (e.g. 'Bag of Holding'). The preview will be correct, but the link will be `https://5e.tools/items/items.html#bag%20of%20holding_dmg` instead of `https://5e.tools/items/bag-of-holding-dmg.html` or `https://5e.tools/items.html#bag%20of%20holding_dmg`

Browser (Chromium, Firefox, Edge, etc): Firefox

Platform (Windows, iOS, Android, etc): Windows 10

**Comment by TheGiddyLimit** [comment]
Wait, what? How did you even get to this page in the first place :thinking: These individual-item pages aren't linked from anywhere on the site, and _so far as I know_ aren't indexed by Google (yet).

Nonetheless, cheers, will fix that.

**Comment by AblingerOscar** [comment]
It came up when googling for an item ^^
I forgot which one it was, so I can't send you the link to the search, where it came up as 2nd or 3rd result, sadly, however when restricting it to the site, those links are the first that come up – at least for some items. Example search term: [bag of holding site:https://5e.tools](https://www.google.com/search?hl=en&as_q=bag+of+holding&as_epq=&as_oq=&as_eq=&as_nlo=&as_nhi=&lr=&cr=&as_qdr=all&as_sitesearch=https%3A%2F%2F5e.tools&as_occt=any&safe=images&as_filetype=&as_rights=)

**Comment by TheGiddyLimit** [comment]
:eyes: well I'll be, there they are. Looks like they finally got indexed last Wednesday. It was taking its sweet fucking time, so I gave up checking, aside from occasionally Googling "5etools <creature>" (and seeing no results).
Good stuff though; hopefully the search rankings will pick up a bit, will need to see what fun things daddy Goog suggests I do to help this.

**Comment by TheGiddyLimit** [comment]
Should now be fixed.
