### ISSUE TITLE
Basic text box - embedded rolls won't work on Mac

### ISSUE THREAD

**Issue by arthur-bauer** [TheGiddyLimit/TheGiddyLimit.github.io#285]
Please fill out as much of this template as possible/is applicable.

**Is this a bug or a feature request:** Bug

**Issue:** Embedded rolls like `[[1d20+5]]` won't work on Mac (CTRL click opens the right click menu instead)

**Page(s) affected:** <https://5e.tools/dmscreen.html>

**Reproduction steps:** 

1. Open a new DM screen
2. Place a Basic Text Box
3. Type a clickable roll like `Damage: [[2d6]]`
4. CTRL-click on the text to activate it 

Instead of enabling clickable links, the right-click menu opens.

Additional information:

**Browser (Chromium, Firefox, Edge, etc):** Chrome, latest version; Safari, latest version.

**Platform (Windows, iOS, Android, etc):** macos

**Comment by TheGiddyLimit** [comment]
Sadly, repro step 0 is "own a Mac," which I do not. Is CTRL-click to open a context menu a general OS-wide feature?

**Comment by arthur-bauer** [comment]
Yes, it is. Any chance we can change this to another modifier key (optional, if needed)?

**Comment by TheGiddyLimit** [comment]
Is CMD-click used for anything?

**Comment by arthur-bauer** [comment]
Not system-wide, no.

**Comment by TheGiddyLimit** [comment]
Roger that. Will add that for next release, and see what happens :upside_down_face:
