### ISSUE TITLE
[BUG] Bestiary, Ki-Rin image not displayed (wrong file name)

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#286]
VGM. The "R" of ki-rin is uppercase in the image file name but "r" (lowercase) is used in the link.
The token is fine, I'm talking about the image in the "Images" tab.

**Comment by TheGiddyLimit** [comment]
The pain of developing on a Windows machine, where filenames are case-insensitive 😩 
Fixed for next release.
