### ISSUE TITLE
Add page for Actions under References

### ISSUE THREAD

**Issue by MALfunction84** [TheGiddyLimit/TheGiddyLimit.github.io#287]
**Is this a bug or a feature request:** Feature request

**Issue:**

The Player's Handbook and DMG list a number of different actions characters can take. It's helpful to be able to refer to those, especially for what checks are associated with each and circumstances where the character or target has advantage/disadvantage on the check.

**Page(s) affected:** N/A (new page: actions.html)

**Additional information:**

A number of class/creature abilities refer to these actions by name, so linking to them provides additional context.

Here all all the actions and their page numbers.

* Attack (PHB 192)
  * Melee (PHB 195)
    * Mark (DMG 271)
  * Ranged (PHB 195)
  * Disarm (DMG 271)
  * Grapple (PHB 195)
    * Climb onto a Bigger Creature (DMG 271)
  * Shove (PHB 195)
    * Shove Aside (DMG 272)
* Cast a Spell (PHB 192)
* Dash (PHB 192)
* Disengage (PHB 192)
* Dodge (PHB 192)
* Don/Doff a Shield (PHB 146)
* Escape Grapple (PHB 195)
* Help (PHB 192)
* Hide (PHB 192)
* Improvise (PHB 193)
* Overrun* (DMG 272)
* Ready (PHB 193)
* Search (PHB 193)
* Tumble* (DMG 272)
* Use an Object (PHB 193)

*Can also be done as a bonus action.

**Comment by TheGiddyLimit** [comment]
Added for next release.

**Comment by MALfunction84** [comment]
@TheGiddyLimit 
Thanks! I noticed a few are missing:

* Escape Grapple (PHB 195)
* Grapple (PHB 195)
* Shove (PHB 195)

(It occurred to me that "Don/Doff a Shield" is a special case of "Use an Object.")

**Comment by TheGiddyLimit** [comment]
I simply moved the list we had in the PHB over, so it seems those were missing from there. Strange.

There's also "Identify a Spell" (XGE p85).

**Comment by MALfunction84** [comment]
[Grapple](https://5e.tools/book.html#PHB,9,grappling,0) and [Shove](https://5e.tools/book.html#PHB,9,shoving%20a%20creature,0) are types of attacks, so they're subsections under [Making an Attack](https://5e.tools/book.html#PHB,9,making%20an%20attack) later in the chapter. Then [Escape a Grapple](https://5e.tools/book.html#PHB,9,escaping%20a%20grapple,0) is there under Grapple. The layout of this chapter is strange, yeah.

Hmm, looks like "Identify a Spell" is also a reaction. Maybe each action could have tags for whether it can be done as a reaction or bonus action. Some might be only those. Might make a good home for Opportunity Attack and Two-Weapon Fighting.
