### ISSUE TITLE
[BUG] Clicking the border between table entries highlights an entry without displaying it

### ISSUE THREAD

**Issue by brandtmaynard** [TheGiddyLimit/TheGiddyLimit.github.io#288]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Bug.

Issue: When you hover the cursor over the one pixel border between entries on a page like Races, it highlights the above entry as if you were hovering over it. When you click the border, it highlights the above entry as if it were selected and dehighlights the previously selected entry, but it doesn't update the information pane on the right with the selected entry.

Page(s) affected: Every page with a list like Races and Classes, though not lists like Names and Encounter Generator.

Reproduction steps: Go to a page like Races, position the cursor on the border between entries (the lowest pixel which highlights the above entry), click.

Additional information: When the page is zoomed in and the border is larger than one pixel, the issue described above occurs when clicking anywhere on the border.

Browser (Chromium, Firefox, Edge, etc): Google Chrome Version 78.0.3904.97 (Official Build) (64-bit)

Platform (Windows, iOS, Android, etc): Windows 10 version 10.0.17134 N/A Build 17134, Ubuntu MATE 18.04.3 LTS with kernel 4.15.0-66-generic (same version of Chrome)

**Comment by TheGiddyLimit** [comment]
Congratulations, you win the prize for "most dastardly bug report." While I won't be getting the last hour of my life back, this should be fixed for next release.
