### ISSUE TITLE
enhancement(managebrew): include a "don't ask me again" options for confirming homebrew deletion

### ISSUE THREAD

**Issue by hafdon** [TheGiddyLimit/TheGiddyLimit.github.io#294]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Feature

Issue: One must confirm (in a modal) on each homebrew deletion.

Page(s) affected: managebrew.html

Reproduction steps: Click "delete" (trash can icon) button on an imported homebrew

Additional information:

Browser (Chromium, Firefox, Edge, etc): Chrome

Platform (Windows, iOS, Android, etc): Windows, Mac

![image](https://user-images.githubusercontent.com/39073287/72075103-132cc700-32c1-11ea-8e6b-f0cc67c9ff07.png)

**Comment by TheGiddyLimit** [comment]
That's not really a solution, though, it just slightly moves the pain. What it really needs is an undo/redo feature, so that deleting things would never be a problem.
