### ISSUE TITLE
(Request) External Search in URL as well as name

### ISSUE THREAD

**Issue by ChaoDjinn** [TheGiddyLimit/TheGiddyLimit.github.io#296]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request:
Feature Request.

Issue:
When searching in the manage external art browser, it would be amazing if it also searched the URL, some of the collections I browse have the collection name as the name, not the individual tokens. The URL has the actual token name such as "dwarf" etc. I might try and implement it myself over the next few days while off work and create a pull request. It's a massive piece of code though so figure you'd be able to add it super quick! Kudos to you. Amazing work.

Page(s) affected:

Reproduction steps:

Additional information:

Browser (Chromium, Firefox, Edge, etc):

Platform (Windows, iOS, Android, etc):

**Comment by TheGiddyLimit** [comment]
From what I remember of the code that would be easy enough to implement, likely a 15-minute job at worst.
Just out of interest, why open the issue here? The art browser isn't related to this repo.
