### ISSUE TITLE
Full-body search

### ISSUE THREAD

**Issue by TotallyTheAdmin** [TheGiddyLimit/TheGiddyLimit.github.io#299]
Is this a bug or a feature request: feature request

Issue: Searching for items only searches for their names. Optionally searching their description would also be useful.

Page(s) affected: items, spells etc.

Additional information: I'm aware of #253 and the implications, however, I feel like an _optional_ full-body search for only parts (e.g. items, spells, not the entire website) would be quite useful – maybe with an disclaimer that it's gonna be slow(er)*.

Is this something that you'd be interested in?

*isn't that data already loaded anyways? at least items.json let's me think that

**Comment by TheGiddyLimit** [comment]
There's a suggestion for this open in our Discord, where you can vote for it.
