### ISSUE TITLE
[Suggestion] Items, Images, Greater Silver Sword (MTF, p89)

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#301]
Hi,
If you want, there's an image of the Greater Silver Sword in MTF.
Conveniently, it's also in the digital version for Fantasy Grounds,
where it's called Ch-4-2.jpg, 1,6 Kb.

Bye ^^

**Comment by TheGiddyLimit** [comment]
Cheers, added for next release
