### ISSUE TITLE
Attributes above 15 generated when pressing Random button in pointbuy statgen

### ISSUE THREAD

**Issue by darodrigues** [TheGiddyLimit/TheGiddyLimit.github.io#305]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Bug

Issue: Random button in pointbuy can randomly generate impossible values

Page(s) affected: statgen.html#pointbuy

Reproduction steps: 
Open 5e.tools/statgen#pointbuy
Click Random a few times
Sometimes a 16 comes up in an attribute. I have personally witnessed a 19

Additional information:

Browser (Chromium, Firefox, Edge, etc):
Mozilla Firefox and Google Chrome

Platform (Windows, iOS, Android, etc):
Windows

**Comment by darodrigues** [comment]
It seems the anonymous function raises the value of the attribute before running the getCostAndValue, which returns cost 0 for a value not on the cost table. This way, when the attribute gets raised to 16, it doesn't cost anything, the budget doesn't get to be reduced, and the loop keeps on truckin'. It may be that either the `randomise.click()` function needs to check if `Number($toBump.val())` is out of bounds  and reject it, or the `getPointBuyCost(n)` needs to return some arbitrarily large number if `n` is greater than `statMax()`

**Comment by TheGiddyLimit** [comment]
I'm not sure I follow. What do you have in your "Custom Rules" table?

**Comment by darodrigues** [comment]
Nothing. The "custom rules" checkbox is unmarked, and in any case I haven't modified the attribute costs. The "random" button randomly raises some attributes above the limit, and I suspect it's due to a wrap around in the attribute cost list. It doesn't happen _all_ of the time, but it does happen often enough. I usually can get a 16 or higher within 10 clicks of that button.
![screenshot1](https://user-images.githubusercontent.com/8304536/80778484-f271d100-8b3e-11ea-90b5-41bd08d258c1.png)
![screenshot2](https://user-images.githubusercontent.com/8304536/80778486-f3a2fe00-8b3e-11ea-8b52-1ce901945707.png)

**Comment by TheGiddyLimit** [comment]
Fair enough. Fixed for next release, cheers
