### ISSUE TITLE
Class Page not Working

### ISSUE THREAD

**Issue by CPUZwolfy** [TheGiddyLimit/TheGiddyLimit.github.io#307]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request:

Issue: The Class page does not show any of the classes in the list, doesn't seem to be reading the 'class.js' file.

Page(s) affected: https://5e.tools/classes.html

Browser (Chromium, Firefox, Edge, etc): Opera

Platform (Windows, iOS, Android, etc): Windows

Images:
![image](https://user-images.githubusercontent.com/68321039/87515905-28a0f600-c642-11ea-90b8-bc45d59107c2.png)
![image](https://user-images.githubusercontent.com/68321039/87515935-38b8d580-c642-11ea-9fad-ee4eab4d4af1.png)

**Comment by TheGiddyLimit** [comment]
Clear your cookies, or try [noads.5e.tools](https://noads.5e.tools).
