### ISSUE TITLE
table for Potions of Healing

### ISSUE THREAD

**Issue by pepper-jk** [TheGiddyLimit/TheGiddyLimit.github.io#311]
Is this a bug or a feature request:

**feature request**

Issue:

There is no table for the **potions of healing**

Reproduction steps:

Search for **potions of healing** (or "potion of healing", "heal" or "potion") and you wont find a table like [this](https://www.dndbeyond.com/magic-items/potion-of-healing).

**Comment by TheGiddyLimit** [comment]
Added for next release, cheers.
