### ISSUE TITLE
Current bestiary import in Initiative tracker overwrites Players.

### ISSUE THREAD

**Issue by pepper-jk** [TheGiddyLimit/TheGiddyLimit.github.io#312]
### Is this a bug or a feature request:

**Bug**

### Issue:

Current bestiary import in Initiative tracker overwrites Players.

### Page(s) affected:

DM screen - Initiative Tracker (DM View)

### Reproduction steps:

- Add players to tracker, give them names.
- Optionally: add init as well as HP or additional columns.
- Import **_from current bestiary encounter_**.

The players will have been removed and 4 new empty ones will have been added.

### Additional information:

It is also possible that the other imports cause the same problem. Haven't tested it yet.

### Browser (Chromium, Firefox, Edge, etc):
Chromium Version 84.0.4147.105 (Official Build) Arch Linux (64-bit)

### Platform (Windows, iOS, Android, etc):
Arch Linux x86_64
5.7.12-arch1-1

**Comment by TheGiddyLimit** [comment]
Working as intended. You can specify players in the encounter builder, which will be imported too.
