### ISSUE TITLE
MacOS/Firefox does not render the items page correctly

### ISSUE THREAD

**Issue by chronoviking** [TheGiddyLimit/TheGiddyLimit.github.io#314]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Bug

Issue: Viewing the "Items" page, the screen does not render the columns correctly. Instead of two columns side-by-side, it renders everything full-width. 

The bigger issue is that there is no scrolling on pages. This means that the page is the filter stacked on top of the mundane item stacked on top of magic items. This leaves little if any room to display an item description. On my MacBook, I can only see the title and weight of an item, no description. In order to read anything I need to shrink the filter and if possible show only magic or mundane items.

This does not affect any of the other similarly designed pages (Race, Spells, Bestiary, etc). This does not affect Chrome on the same machine. I have not seen this issue on Windows machines

Page(s) affected: Items

Reproduction steps: Navigate to the Items page using Firefox on a Mac

Additional information:

Browser (Chromium, Firefox, Edge, etc): Firefox 79.0, Chrome 84.0.4147.105

Platform (Windows, iOS, Android, etc): Mac 10.15.5

**Comment by TheGiddyLimit** [comment]
iOS is "unsupported" insofar as I have no device that runs it with which I can test/debug. Could you please provide a screenshot?

**Comment by chronoviking** [comment]
<img width="1513" alt="Screen Shot 2020-08-25 at 3 56 45 PM" src="https://user-images.githubusercontent.com/5943375/91238261-81f44e80-e6f1-11ea-8a6d-2dacd7979571.png">

As you can see, the filters go across the screen, causing the item description box to show up at the bottom of the screen, almost completely out of view.

**Comment by TheGiddyLimit** [comment]
I see. It's set to switch based on purely CSS screen width rules, and those rules are the same on every page. I would be willing to bet this is a bug in Firefox itself. If it only appears on iOS (and I therefore have no way to reproduce it) I'm not going to spend time blindly groping in the hopes of accidentally fixing it.

**Comment by djeikyb** [comment]
On firefox 85, macos 11.2, site v1.122.8, works for me. I can scroll in both the mundane and magic panes, as well as the page. If I shrink the window a good bit, it gets harder to use, but even at 768 pixels wide there's enough side margin to scroll down.

Btw OP claims to be using firefox on macos catalina, not an iphone or ipad.
