### ISSUE TITLE
Printable Version of Statblock Generator

### ISSUE THREAD

**Issue by ChiefMilesEdgeworth** [TheGiddyLimit/TheGiddyLimit.github.io#316]
Is this a bug or a feature request:
Feature request

Issue:
Printable Statblocks

Page(s) affected:
Homebrew generator, statblock viewer

Reproduction steps:
N/A

Additional information:
It would nice to be able to generate a printable format for the homebrew creator. This would make the tool more friendly as a supplemental tool for DMs rather than requiring that they have access to their laptop during a session

Browser (Chromium, Firefox, Edge, etc):
All

Platform (Windows, iOS, Android, etc):
All

**Comment by TheGiddyLimit** [comment]
Supporting printing is something I wish to do less, not more, of. That being said, supporting exports of data formats that can be used in other sites/statblock visualizers is potentially do-able; the existing "RPG Cards" integration, for example.
