### ISSUE TITLE
Missing Sidekicks cards in Dragon of IceSpire Peak

### ISSUE THREAD

**Issue by Alby1987** [TheGiddyLimit/TheGiddyLimit.github.io#318]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: missing content

Issue: I noticed that the Dragon of IceSpire Peak adventure is missing information about the sidekicks: there are stats and rules, but the page is missing the actual sidekicks (name and photos) that are provided in a separate card deck

Page(s) affected: Dragon of IceSpire peak

**Comment by TheGiddyLimit** [comment]
Cheers, fixed for next release.
