### ISSUE TITLE
Missing data on Sleeping Dragon's Wake D13 Area

### ISSUE THREAD

**Issue by Alby1987** [TheGiddyLimit/TheGiddyLimit.github.io#319]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: bug

Issue: At the end of D13 (Magazine) there is a link error on Area D7, putting a lot of the text following that link in the link itself (a brace is not closed)

Page(s) affected: https://5e.tools/adventure.html#sdw,4,d13.%20magazine,0

**Comment by TheGiddyLimit** [comment]
Fixed for next release.
