### ISSUE TITLE
Spells page broken

### ISSUE THREAD

**Issue by mattnaz** [TheGiddyLimit/TheGiddyLimit.github.io#32]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Bug

Issue: Spell's filterbox and display is broken

Page(s) affected: Spells

Reproduction steps: Go to the spells page filter box and display pane do not load properly

Additional information: Dev console in Chrome shows the following: 
````
Uncaught ReferenceError: MultiFilter is not defined
    at spells.js:1
spells.js:1 Uncaught ReferenceError: filterBox is not defined
    at pageInit (spells.js:1)
    at _onIndexLoad (multisource.js:1)
    at multisource.js:1
    at XMLHttpRequest.s.onload (utils.js:1)
````
Browser (Chromium, Firefox, Edge, etc): Chrome and Safari

Platform (Windows, iOS, Android, etc): OSX(Chrome and Safari) and Android(Chrome)

**Comment by TheGiddyLimit** [comment]
Clear your browser cache (CTRL+F5 on the page). It's working.

Did you encounter this on http://thegiddylimit.github.io/ or https://5etools.com/ ?

**Comment by mattnaz** [comment]
You're right it was a cache issue.

**Comment by TheGiddyLimit** [comment]
Glad to hear it. Server admin had a plan in the works to deal with such things, I'll have to poke him for a status update.

**Comment by mattnaz** [comment]
Yeah it could be solved with a cache age setting in nginx/apache. Although there is a balancing act of the right age so people aren't always downloading the js/css files. If you haven't already you may want to explore generating unique asset file names with grunt/gulp/etc.

**Comment by TheGiddyLimit** [comment]
We've fixed it, hopefully, by appending query strings with a version number to the JS `src`s. A site-wide version number mind you, so still a little clunky, but it ought to do the job.
