### ISSUE TITLE
New touch icons not showing

### ISSUE THREAD

**Issue by jpcranford** [TheGiddyLimit/TheGiddyLimit.github.io#324]
**Is this a bug or a feature request:** Bug

**Issue:** Old touch icon is still shown in many places, due to browser cache. This is present for example in the Favorites view on all versions of Safari, tested and listed below, and possibly more.

![1ADC4139-376A-4B8F-AC1B-C813ACE4D4C6](https://user-images.githubusercontent.com/21347202/98470483-20e20000-21a3-11eb-851b-31f2ab46c928.jpeg)

This is present even when deleting the bookmark, force-closing Safari, and then re-adding the bookmark.

This isn’t an issue with the desktop version of Safari, because that recaches the touch icons from the live site every time the app is opened.

**Page(s) affected:** all

**Reproduction steps:** N/A

**Possible Solution:** Append a false query (such as `?v=1.114.2`) to the `href` URLs of the icons, to trick the browser into updating its cached version.

**Browser:** Safari

**Platform:** iOS, iPadOS

**Comment by jpcranford** [comment]
I’m out right now, but when I get home I’ll hook my devices up to my computer and test the fix in Dev mode.

**Comment by TheGiddyLimit** [comment]
Closing as inactive
