### ISSUE TITLE
Creature specific - wrong stats

### ISSUE THREAD

**Issue by Mavrick593** [TheGiddyLimit/TheGiddyLimit.github.io#325]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Bug?

Issue: The saving throw and skill bonuses are off by +1 for Zephyros in the Bestiary. It appears at a casual glance that maybe the creature's "proficiency" is being calculated incorrectly. Either by its number of hit dice or its CR (which is higher than the base stat block Zephyros is based on, a Cloud Giant), I'm not sure how that is down in the background.

I don't know if this is the right place to report this sort of thing, this is the first time I've done it. I was just looking for somewhere to report it and this is what I came up with.

I don't know for sure if this is happening on other entries in the Bestiary, but I would imagine so, especially for any NPC entries that are based on a basic monster's stat block.

Page(s) affected: Bestiary (Zephyros, maybe others)

Reproduction steps: Check the Bestiary entry

Additional information: I only noticed this when comparing the stats to the published books. From what I researched there was no errata that matches the website's information, thus I think something is wrong with how the site is calculating those numbers. The initial red flag was because the Perception bonus and passive Perception numbers for Zephyros don't match up.

Browser (Chromium, Firefox, Edge, etc): Chrome

Platform (Windows, iOS, Android, etc): Windows

**Comment by TheGiddyLimit** [comment]
Zephyros is CR 13, which gives him a proficiency bonus of +5. The numbers on the site are "correct" according to the math of the system. There are various bits of "community" errata in the site, fixing clear typos such as this.
