### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by david-simoes-93** [TheGiddyLimit/TheGiddyLimit.github.io#327]
https://github.com/TheGiddyLimit/TheGiddyLimit.github.io/blob/master/data/class/class-paladin.json#L2025

The aura increases to 30ft, not 10ft. Sorry I couldn't make a PR, no time!

**Comment by TheGiddyLimit** [comment]
Apologies, that line number no longer goes to the right place. Which feature has the typo?
