### ISSUE TITLE
FeatureRequest: LaTeX renderer

### ISSUE THREAD

**Issue by spirritus** [TheGiddyLimit/TheGiddyLimit.github.io#328]
Hello there,

this is an amazing tool! The central data storage in json as well as the use of different renderers allows for various output formats. Currently HTML and Markdown are supported. 

I am interessted in writing an additional renderer for LaTeX and the dnd5 template at https://github.com/rpgtex/DND-5e-LaTeX-Template

Could you give some pointers where to start this project?

Best regards
Jens

**Comment by TheGiddyLimit** [comment]
I have no knowledge of, nor interest in, LaTeX, so I would be hesitant to add this feature, given that I wouldn't be able to maintain it.

If you're intent on maintaining it yourself, then you can look at, as you've mentioned, how the Markdown renderer plugs in (there's another renderer for the "RPG cards" site that works the same, if you want another example). The UI would have to be tweaked to add some "export as LaTeX buttons" somewhere, but I can handle that as and when.
