### ISSUE TITLE
Optional Class Feature references

### ISSUE THREAD

**Issue by rogueturnip** [TheGiddyLimit/TheGiddyLimit.github.io#332]
It seems the option class feature reference pages are off. 
![image](https://user-images.githubusercontent.com/7782364/101969909-0523ac80-3bdc-11eb-9b5e-4cc7b640fe9f.png)
Shows the Rogue Steady Aim from TCE as p24.  When I look at the JSON it is on page 62.  When checking TCE p24 is the barbarian one.

**Comment by TheGiddyLimit** [comment]
Intentional; the alternative is to have the same "rule" listed once per class, which is not preferable.
