### ISSUE TITLE
Bug reports data missing

### ISSUE THREAD

**Issue by aronFF** [TheGiddyLimit/TheGiddyLimit.github.io#333]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request:
feature

Issue:
Hard to find anywhere to report bugs related to 5e tools. Is this the right place?

Page(s) affected:

Reproduction steps:

Additional information:

Browser (Chromium, Firefox, Edge, etc):

Platform (Windows, iOS, Android, etc):

**Comment by TheGiddyLimit** [comment]
Here works, although generally the best place to report issues is on our [Discord](https://discord.gg/nGvRCDs).
