### ISSUE TITLE
Reading Aids

### ISSUE THREAD

**Issue by DonaldTsang** [TheGiddyLimit/TheGiddyLimit.github.io#334]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Feature Request

Issue: Increase Readability by highlighting keywords and substituting common words with Emoticons
- Advantage/Disadvantage
- AC, DC, and attack roll
- STR, DEX, CON, INT, WIS, CHA
- Action, Bonus Reaction, Reaction
- Concentration
- foot, mile, minute, turn, round
- short rest, long rest
- (maybe) conditions and skills

**Comment by TheGiddyLimit** [comment]
No thanks.
