### ISSUE TITLE
Telekinesis does not show up when filtering for spells with strength checks

### ISSUE THREAD

**Issue by ThatOne4205** [TheGiddyLimit/TheGiddyLimit.github.io#335]
Is this a bug or a feature request: Bug

Issue: When filtering spells for ones involving strength checks, telekinesis does not show up in the list of spells, despite calling for strength checks to resist the spell's effects.

Page(s) affected: Spells

Reproduction steps: Go to Spells page,  filter for Str. Check.

Browser (Chromium, Firefox, Edge, etc): Google Chrome version 88.0.4324.150

Platform (Windows, iOS, Android, etc): Windows 10

**Comment by TheGiddyLimit** [comment]
Fixed for next release.
