### ISSUE TITLE
Render subclass name at the beginning of each class feature

### ISSUE THREAD

**Issue by MALfunction84** [TheGiddyLimit/TheGiddyLimit.github.io#337]
The TCE subclasses include a line at the top of each feature that names the subclass. For example, here:
https://github.com/TheGiddyLimit/TheGiddyLimit.github.io/blob/ed681af70f7d6bd68f4d2f9a0ea5db4bdf133c6a/data/class/class-rogue.json#L1980

This is really helpful and should be added to all subclass features from all other sources.

When a user selects multiple subclasses to view at once, a level that grants a subclass feature will show features from all the selected subclasses together. As more subclasses are selected, it becomes increasingly difficult to determine which subclass is the source of a given feature at that level, particularly when the selected subclasses are scrolled off-screen. Showing the subclass with each feature would make this very clear.

**Comment by TheGiddyLimit** [comment]
Please submit any such requests/suggestions via our [Discord](https://discord.gg/nGvRCDs) in future, where there's a voting system in place for new feature suggestions.

That being said, this is actually a bug/regression, and as such, has been fixed for next release.
