### ISSUE TITLE
Feature Request: Compare Creatures

### ISSUE THREAD

**Issue by pepper-jk** [TheGiddyLimit/TheGiddyLimit.github.io#338]
## Feature request

**Issue:** Compare Creatures

**Page(s) affected:** Bestiary

**Use cases:**
- comparing minions to their boss monster
- comparing different variants or ages (e.g. for dragons)
- comparing a modified creature (homebrew) to the original
- comparing power levels of creatures (other then with just CR)
  - to hit
  - spell save DC
  - spells prepared
  - actions (e.g. multiattack, parry)

### Additional information

This feature would provide a GUI element to compare (two or more) creature statblocks and highlighting differences, while still displaying the equal parts.

I'm not 100 percent sure about UI elements for this, as my experience in UI is limited.

The only examples I could give off the top of my head would be **(side by side) diffs from github** and comparison style used by [ark.intel.com](https://ark.intel.com/content/www/us/en/ark/compare.html?productIds=/88193,88180,84695,75105).

### possible requirements
- actions compared by name and notable modifiers (save DC, to hit)
  - should ignore different creature name (obviously)
  - number of attacks in *multiattack* should be compared
- order of traits or actions should not make a difference

**Comment by revilowaldow** [comment]
Looks cool, please submit the suggestion on the discord so it can be tracked and voted on?

**Comment by TheGiddyLimit** [comment]
Closing as this is now in Discord
