### ISSUE TITLE
[Bug] CR calculator, something is wrong

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#34]
[Check this link](https://thegiddylimit.github.io/crcalculator.html#0,27,22,18,4,false,Medium,6,10,false,0,false,0,traits:)
Offensive CR 2
Defensive CR 2
Challenge Rating 1/2

**Comment by TheGiddyLimit** [comment]
DBAWiseMan claims to have fixed this.
