### ISSUE TITLE
Crawling claw tokens not linked correctly to character sheet in WDH

### ISSUE THREAD

**Issue by oetlinge** [TheGiddyLimit/TheGiddyLimit.github.io#340]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request:
bug

Issue:
Crawling Claw tokens on the mausoleum winter page of Waterdeep Dragon Heist are not correctly linked to the corresponding character sheet.

Page(s) affected:
Mausoleum winter

Reproduction steps:
1. Import the mausoleum winter map from WDH via the roll20 module importer/exporter
2. Open the settings for the crawling claw tokens located in the tomb (observe the tokens are not linked to the character sheet)

Additional information:

Browser (Chromium, Firefox, Edge, etc):

Platform (Windows, iOS, Android, etc):

Changing according to the screenshot should resolve the issue. There are 6 instances in total.
![image](https://user-images.githubusercontent.com/59981506/117520827-47c59700-af78-11eb-94d7-c6d64762dce0.png)

**Comment by TheGiddyLimit** [comment]
Cheers, fixed for next release.
