### ISSUE TITLE
Brew of Fey Folio by Mage Hand Press

### ISSUE THREAD

**Issue by carsonmcgorry** [TheGiddyLimit/TheGiddyLimit.github.io#343]
Hello,
I've made homebrews using the homebrew builder of the spells, creatures, and NPCs of Mage Hand Press's Fey Folio book. The pastes are here:
https://pastebin.com/LQmDSEKa
https://pastebin.com/JLdN6sc8
They should be complete, aside from a couple small instances of missing integration with some of MHP/Middle Finger of Vecna's player classes that are not currently on 5etools. It does not contain the subclasses or magic items contained in the book—only the spells and creatures.

Thanks,
-Carson

**Comment by TheGiddyLimit** [comment]
Good stuff, but this isn't the place for homebrew. If you could PR them against the [homebrew repo](https://github.com/TheGiddyLimit/homebrew/pulls), that would be great
