### ISSUE TITLE
bestiary, vgm, bheur hag additional lair action is wrong

### ISSUE THREAD

**Issue by Temp345bis** [TheGiddyLimit/TheGiddyLimit.github.io#347]
Hello, former Temp345 here (los email account associated to that and had to create a new github account)

BUG
The additional lair action of the bheur hag is using the one from the Green Hag (illusory duplicate...) instead of

_The hag creates a blizzard in a 40-foot-high, 20-foot
radius cylinder centered on a point she can see within
120 feet of her. The effect lasts until initiative count
20 on the next round. The blizzard lightly obscures
every creature and object in the area for the duration.
A creature that enters the blizzard for the first time on
a turn or starts its turn there is blinded until initiative
count 20 on the next round._

Link: https://noads.5e.tools/bestiary.html#bheur%20hag_vgm

Here you can see the (correct) info from VGM: https://noads.5e.tools/book.html#vgm,0,lair%20actions,0

I tried to fix it myself but can't find where that data is stored
(doing a "grep" for the wrong lair action text only showed a match from book-vgm.json)

Additional information:
Browser: Firefox 91.0.1 (64bit)
Platform: Linux 64bit

Thanks for all your hard work. Bye ^^

**Comment by TheGiddyLimit** [comment]
👍 fixed both for next release. We do try to correct maths for skills/saves/etc. where they show up and are reasonably unambiguous
