### ISSUE TITLE
Sun Blade is listed as not needing attunement

### ISSUE THREAD

**Issue by Konahrik13** [TheGiddyLimit/TheGiddyLimit.github.io#35]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Bug

Issue: Sun Blade doesn't have "(Requires Attunement)" when it does need it.

Page(s) affected: Sun Blade in Items.

Reproduction steps:

Additional information:

Browser (Chromium, Firefox, Edge, etc):

Platform (Windows, iOS, Android, etc):

**Comment by TheGiddyLimit** [comment]
Fixed by #36.
