### ISSUE TITLE
[IDEA] Bestiary, referencing spells not from PHB and links to items or other creatures

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#38]
EDIT: the markdown is not working for some reason, so the formatting (bold text) isn't showing.

I was thinking about a way to fix the problem of creatures with spells not from the PHB (e.g. Aerisi, storm sphere).
What about adding to the spell name a suffix with the (non default) source?
bestiary-pota.json : 	4th level (3 slots): ice storm, storm sphere**_xge**

Then, in bestiary.js, function loadhash, instead of:
```
for (let i = 0; i < spellslist.length; i++) {
	spellslist[i] = "<a href='spells.html#" + encodeURIComponent((spellslist[i].replace(/(\*)| \(([^)]+)\)/g, ""))).toLowerCase().replace("'", "%27") + "_" + "phb' target='_blank'>" + spellslist[i] + "</a>";
	if (i !== spellslist.length - 1) spellslist[i] = spellslist[i] + ", ";
}
```
Use something like:
```
for (let i = 0; i < spellslist.length; i++) {
	**spellsSource = "phb"; // default, so you don't have to use any suffix
	if (spellslist[i].includes("_") {
		// updates spellsSource and remove suffix from spellslist[i]
	}**
	spellslist[i] = "<a href='spells.html#" + encodeURIComponent((spellslist[i].replace(/(\*)| \(([^)]+)\)/g, ""))).toLowerCase().replace("'", "%27") + "_" **+ spellsSource +**"' target='_blank'>" + spellslist[i] + "</a>";
	if (i !== spellslist.length - 1) spellslist[i] = spellslist[i] + ", ";
}
```

Probably not a very elegant solution, but ATM I don't have anything better
(this is not a big deal, there are only a handful of creatures that uses spells not from the PHB).

.
.
.

I'd like to have (I would make the updating myself) links to the related items for the
Special Equipment trait of some creatures (e.g. Ezmeralda) and also links for summoned
creatures (e.g. Glabrezu).
I think that using directly `<a href=... target='_blank'>` isn't very neat, I'd like to use the syntax used by adventures:
{@item ...}
{@creature ...}
But the json(s) of the bestiary contains plain text, not "entries" (so the entryRenderer that
handles those shortcuts/macros/whateverTheyAre isn't used).

Sorry for the bad English and for not being familiar with javascript or how 5etools works internally.

**Comment by TheGiddyLimit** [comment]
> But the json doesn't contain "entries" (to call upon entryRenderer), just plain text.

You've hit the nail on the head there -- the solution is to convert the JSON to "entries" so we _can_ use {@tag ...}s, which will fix spells, too.

Made a link-checker test/script yesterday that validates every {@tag} in every JSON file, so automating the process and catching any problems should be fairly simple.

Regardless, the way spells are stored in the JSON is nasty, and needs to be overhauled. I'm going to end up doing it when I come to fix spellcaster importing into roll20, if not before. It'll all be better Soon:tm:.

**Comment by TheGiddyLimit** [comment]
This is being handled by DBAWiseMan, should be fixed pretty soon.
