### ISSUE TITLE
[Bug] Adventure, Search, Broken Links

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#39]
Browser: Firefox 57.

The search results links don't work. I think because they are case sensitive.

Example: if I select the adventure Out of the Abyss, press F, type "quenthel"
and press ENTER, I got this link as first result:
https://thegiddylimit.github.io/adventure.html#oota,14,the%20way%20of%20lolth
which doesn't work, while if I use
https://thegiddylimit.github.io/adventure.html#OotA,14,The%20Way%20of%20Lolth
it works

**Comment by TheGiddyLimit** [comment]
I think I fixed this earlier. Can you check if it's still a problem? CTRL-F5 the page first, just to be sure.

**Comment by Temp345** [comment]
Still not working.

**Comment by TheGiddyLimit** [comment]
Oh, wow, I see what it is. File paths on Windows are case insensitive. File paths on Linux are case sensitive. I'm testing this on a Windows machine; every sensible server owner in the world runs Linux. Will fix.

**Comment by TheGiddyLimit** [comment]
Okay, it works for me now, 100% (with CTRL-F5ing, at least). Noticed another bug, where things don't get highlighted if they're within lists; will look into fixing that too.
