### ISSUE TITLE
Adventure ROT Epi 3, left sb link to Varram is broken

### ISSUE THREAD

**Issue by l9f** [TheGiddyLimit/TheGiddyLimit.github.io#50]

**Comment by l9f** [comment]
so is the sstckal link

**Comment by l9f** [comment]
Actually, quite a few of the left sidebar links are busted on ROT. Recommend looking at the code that's genning that.

**Comment by TheGiddyLimit** [comment]
The "code" was me copy-pasting those from the PDF contents pages lol. 

Fixed Varram, Ss'tck'al ought to be working, but it doesn't, so there's likely a bug somewhere. Will look into it later.

**Comment by l9f** [comment]
Heheh. I thought it was code gen'd. No rush. Just figured better to make the issue. :)

**Comment by l9f** [comment]
I think you have a caching issue too... Links sometimes start magically working after refreshing the cache after clicking a different top level drop down on the sidebar menu.
