### ISSUE TITLE
Adventures: missing apendices

### ISSUE THREAD

**Issue by TheGiddyLimit** [TheGiddyLimit/TheGiddyLimit.github.io#52]
Do a pass to make sure we're not missing any meaning full content; perhaps even put in a page with links to relevant bestiary/item entries.

**Comment by TheGiddyLimit** [comment]
SKT: 
Appendix A
Appendix C (take fluff content + link to bestiary)

**Comment by TheGiddyLimit** [comment]
CoS:
App A: link to backgrounds
App D: add fluff; link to statblocks
App E: add
App F: add

**Comment by BigJoeDuke** [comment]
Hey there! I'm extremely new to this github thing, and I'm no code monkery, but in the Tortle Package I have found several unlinked items, and a couple of things missing, I have looked at all the source code and figured out how to fix the missing links, but I do not know what to do from here.  Please excuse me if this is not the proper place, but I'd like to help out and contribute if I could.

**Comment by TheGiddyLimit** [comment]
Always happy to accept contributions. You've at least two choices:

- Send me the files, and I'll take care of it (paste into Pastebin; Dropbox link; whatever suits, really).
- Do the GitHub thing, e.g. [https://gist.github.com/Chaser324/ce0505fbed06b947d962](follow this guide).

---
And this isn't the proper place, but GitHub doesn't have much in the way of communication methods. The best you can do is create your own issue, instead of commenting on an old one.

**Comment by TheGiddyLimit** [comment]
Still missing:
- OotA App. B/C/D
- TftYP App. A/B
- ToA App. D/E/F
