### ISSUE TITLE
Adventures ROT epi3: headings missing room numbers. 

### ISSUE THREAD

**Issue by l9f** [TheGiddyLimit/TheGiddyLimit.github.io#59]
Makes it hard to play. :)

**Comment by l9f** [comment]
Saw you closed this... any particular reason why? It's impossible to use the adventure as is if the headings don't correspond to the map room numbers. This was in the main text, not necessarily the left sidebar.

**Comment by l9f** [comment]
I.e. `Entrance Plaza` needs to be `1. Entrance Plaza` and so on and so forth.

**Comment by TheGiddyLimit** [comment]
Yep; it's fixed. I generally don't update the site more than once a day, since it causes havoc for the caching, so I was going to finish up some other things and update it all at once (such as the class page spells). But I'll push it to the GitHub version now.

**Comment by l9f** [comment]
Oh thanks. (I just clone your reposts host locally  and I didn't see the changes)
