### ISSUE TITLE
Spells missing hyperlinks in Classes and Races pages

### ISSUE THREAD

**Issue by akindofcode** [TheGiddyLimit/TheGiddyLimit.github.io#60]
Is this a bug or a feature request: Feature Request / Bug??

Issue: The spells in the races and classes pages don't have hyperlinks to the spell page

Page(s) affected: races.html, classes.html

Reproduction steps:

Additional information:

Browser (Chromium, Firefox, Edge, etc):

Platform (Windows, iOS, Android, etc):

**Comment by TheGiddyLimit** [comment]
Yep, because they're added manually. The alternative (e.g. what roll20 SRD does) is to auto-detect them, but this leads to strange things like every instance of the word "shield" being a link to the spell. If you tell me where the missing ones are, I can easily fix them.

**Comment by akindofcode** [comment]
Artificer: detect magic, identify, revivify 
Barbarian: beast sense, speak with animals, raise dead, augury, clairvoyance, commune with nature

**Comment by akindofcode** [comment]
Aasimar (DMG): light, lesser restoration, daylight 
Aasimar (all of them): light
Dwarf (Duergar):  Enlarge/Reduce, Invisibility 
Elf (Drow): faerie fire, darkness 
Elf (Eladrin): misty step
Firbolg: detect magic and disguise self
Genasi (Air): levitate 
Genasi (Earth): pass without trace 
Genasi (Fire): produce flame, burning hands 
Genasi (Water): shape water, create or destroy water
Gnome (Forest): minor illusion
Half-Elf (Drow Descent): dancing lights, darkness 
Tiefling (Infernal): thaumaturgy, darkness
Tiefling (Variant Infernal): hellish rebuke, darkness, charm person, enthrall, burning hands, darkness 
Triton: fog cloud, gust of wind, wall of water
Yuan-ti Pureblood: poison spray, animal friendship, suggestion

**Comment by akindofcode** [comment]
That should be all!

**Comment by TheGiddyLimit** [comment]
You're a hero. I sure hope you didn't do that by hand 🤔 

Either way, I'll add 'em soon.

**Comment by akindofcode** [comment]
By hand it was, hope I haven't missed many

**Comment by l9f** [comment]
@akindofcode That was awesome help!

**Comment by TheGiddyLimit** [comment]
Should be done. Hopefully _I_ didn't miss any, either.

**Comment by akindofcode** [comment]
Thank you @TheGiddyLimit, probably should have done it myself now that I see how it works!
