### ISSUE TITLE
Nonhuman deities in deities page missing

### ISSUE THREAD

**Issue by darodrigues** [TheGiddyLimit/TheGiddyLimit.github.io#62]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: bug

Issue: Nonhuman deities, despite being present in the JSON, aren't listed in the page, and selecting "nonhuman" in the pantheon filter returns an empty set.

Page(s) affected: deities.html

Reproduction steps: Reset the deities.html filters. Pick a nonhuman deity, such as Yondalla, Tiamat, or Lolth and look for it in the list; none of them are there. Select "nonhuman" as a filter in the pantheon category. The list will become empty.

Additional information: Looking into the JSON, these deities are listed as part of the "Nonhuman Deities" pantheon, whereas the filter is simply "nonhuman". Maybe that's the reason? I still don't get why they don't show up when there are no filters, though.

Browser (Chromium, Firefox, Edge, etc): Chrome 63.0.3239.132 (Official version) 64 bits

Platform (Windows, iOS, Android, etc):

**Comment by Temp345** [comment]
Taking care of this right now

**Comment by darodrigues** [comment]
Or have "Nonhuman Deities" as a category and the proper pantheons for those that do have them. Many races in older editions had but a single creator god, like the kobolds' Kurtulmak or the troglodytes' Laogzed

**Comment by TheGiddyLimit** [comment]
Didn't know about the descriptions in SCAG, will look into adding those. As for grouping things, they're as they are in the book, which is all the information I have. Previous edition content isn't "canon," but if such things are specified in 5e books, then we can add it (although you'll have to tell me where to look).

**Comment by Temp345** [comment]
The Fantasy Grounds module of SCAG also has images for the symbols of the Gods (not for everyone).

**Comment by TheGiddyLimit** [comment]
Interesting. I'll try include those, if they're decent quality.
