### ISSUE TITLE
Typo in Iuz the Evil's entry in deities.html

### ISSUE THREAD

**Issue by darodrigues** [TheGiddyLimit/TheGiddyLimit.github.io#63]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: bug (typo)

Issue: Iuz somehow got typed in as "Luz"

Page(s) affected: deities.html

Reproduction steps: Go to deities.html and search for Iuz (with an "i"). No such god will be found. Now search for Luz (with an "L"). There will be such a god with Iuz's data (portfolio, holy symbol and pantheon)

Additional information: Just a simple typo, but a confusing one, since it affects filtering.

Browser (Chromium, Firefox, Edge, etc): Chrome 63.0.3239.132 (Official version) 64 bits

Platform (Windows, iOS, Android, etc): Windows 10 64-bit

**Comment by Temp345** [comment]
Fixed (waiting for approval)
