### ISSUE TITLE
What help do you need that's not JS? 

### ISSUE THREAD

**Issue by l9f** [TheGiddyLimit/TheGiddyLimit.github.io#65]
I'm a noob on the front end stuff; but I'm fine with json and other programming stuff. What help do you need? Specific proofreading? Data entry? Etc.?

**Comment by TheGiddyLimit** [comment]
I wouldn't ask these things of mine worst enemy, but if you insist, there's plenty that needs done. For example:
Every time a condition ("prone," stunned," etc) is mentioned in text, we want to slap a {@condition <whatever>} tag in there. [See the demo page for some examples](https://5etools.com/demo.html). Bestiary and Adventures are being worked on right now, so best not mess with those. Spells and Classes are ripe for a fix-up, however.

So, for example, in `data/spells/spells-phb.json`'s "Hold Person" text, ` ... succeed on a Wisdom saving throw or be paralyzed for the duration ... ` should become ` ... succeed on a Wisdom saving throw or be {@condition paralyzed} for the duration ...`

**Comment by l9f** [comment]
Sure. I can do that. Simple script in emacs with some manual confirmation. I'll start on spells later this evening.

**Comment by l9f** [comment]
What commit do you want me branching off of? `master` is failing right now with:

```
$ npm test

> 5etools@1.0.0 test /home/l9f/repos/TheGiddyLimit.github.io
> eslint js && stylelint css/style.css && node ./test/alltests.js

##### Validating the JSON schemata #####
/home/l9f/repos/TheGiddyLimit.github.io/test/alltests.js:20
                                console.log(`Testing data/${file}`.padEnd(50), `against schema/${file}`);
                                                                   ^

TypeError: (("Testing data/" + (intermediate value)) + "").padEnd is not a function
    at fs.readdirSync.filter.forEach.file (/home/l9f/repos/TheGiddyLimit.github.io/test/alltests.js:20:40)
    at Array.forEach (native)
    at Object.<anonymous> (/home/l9f/repos/TheGiddyLimit.github.io/test/alltests.js:18:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
npm ERR! Test failed.  See above for more details.
```

**Comment by l9f** [comment]
Majority of Spell conditions are done. That's probably it for me for the week; but I can check in other tasks too. I'll check with you before I do more work.

**Comment by TheGiddyLimit** [comment]
That... shouldn't error, given that [String.prototype.padEnd](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padEnd) is plain-ol' JS. It's fairly new, though, so maybe that's the issue.

**Comment by l9f** [comment]
Classes done with #93.

**Comment by l9f** [comment]
So classes and spells done; what else do you need that is not JS?

**Comment by TheGiddyLimit** [comment]
Thinking about it, fixing the adventures issues in the ripper script is going to be more hassle than it's worth. Might be time I said "fuck it" and opened those up to manual editing. So, if you want to start chewing through the stack of adventures issues, I'd be very happy. I don't see it getting done very soon, otherwise.

In the case of appendices, those missing should be added, but any stat-blocks (creatures, items, etc) should be links to the appropriate page instead of embedded.
