### ISSUE TITLE
Spells: Update Conditions

### ISSUE THREAD

**Issue by l9f** [TheGiddyLimit/TheGiddyLimit.github.io#66]
- [x] Blinded
- [x] Charmed
- [x] Deafened
- [x] Fatigued
- [x] Frightened
- [x] Grappled
- [x] Incapacitated
- [ ] Invisible
- [x] Paralyzed
- [x] Petrified
- [x] Poisoned
- [x] Prone
- [x] Restrained
- [x] Stunned
- [x] Unconscious
- [x] Exhuastion

- [x] Charmed versus charmed in BOLS (also see issue #73)
- [x] Grappled versus grappled in BOLS
- [x] Also see issue #80

Here's the check list for the task.

**Comment by l9f** [comment]
PR submitted for paralyzed https://github.com/TheGiddyLimit/TheGiddyLimit.github.io/pull/67

**Comment by l9f** [comment]
`$ find . -name "*.json" -exec sed -i "s/blinded/{@condition blinded}/g" '{}' \;` for the blinded PR https://github.com/TheGiddyLimit/TheGiddyLimit.github.io/pull/68

**Comment by l9f** [comment]
Charmed done: PR https://github.com/TheGiddyLimit/TheGiddyLimit.github.io/pull/69 

Verified with a grep that all occurrences of charmed were referring to the condition.

**Comment by l9f** [comment]
Question: does `{@condition Charmed}` work? There's on instance in `spells-3pp-bols.json` with a capital `C`harmed that is NOT in PR.

**Comment by l9f** [comment]
Deafened https://github.com/TheGiddyLimit/TheGiddyLimit.github.io/pull/70

**Comment by l9f** [comment]
No PR for **fatigued**; grep found no occurrences in data/spells folder.
```
19:55:10 TheGiddyLimit.github.io/data/spells on  master 
$ grep "Fatigued" ./*

19:55:21 TheGiddyLimit.github.io/data/spells on  master 
$ grep "fatigued" ./*

19:55:25 TheGiddyLimit.github.io/data/spells on  master 
$ 
```

**Comment by l9f** [comment]
Frightened https://github.com/TheGiddyLimit/TheGiddyLimit.github.io/pull/71

**Comment by l9f** [comment]
Grappled: There is one instance of **G**rappled with a capital 'G' in `spells-3pp-bols.json`. I am **not** including it in the following PR https://github.com/TheGiddyLimit/TheGiddyLimit.github.io/pull/72 as I don't know if `{@condition Grappled}` works.

**Comment by l9f** [comment]
Incapacitated: https://github.com/TheGiddyLimit/TheGiddyLimit.github.io/pull/74

**Comment by l9f** [comment]
Petrified: https://github.com/TheGiddyLimit/TheGiddyLimit.github.io/pull/75

**Comment by l9f** [comment]
Poisoned: https://github.com/TheGiddyLimit/TheGiddyLimit.github.io/pull/76

**Comment by l9f** [comment]
Prone: https://github.com/TheGiddyLimit/TheGiddyLimit.github.io/pull/77

**Comment by l9f** [comment]
Restrained: https://github.com/TheGiddyLimit/TheGiddyLimit.github.io/pull/78

**Comment by l9f** [comment]
Stunned: https://github.com/TheGiddyLimit/TheGiddyLimit.github.io/pull/79

**Comment by l9f** [comment]
Unconscious: https://github.com/TheGiddyLimit/TheGiddyLimit.github.io/pull/81

**Comment by l9f** [comment]
Exhaustion: https://github.com/TheGiddyLimit/TheGiddyLimit.github.io/pull/82

**Comment by l9f** [comment]
Well, that leaves pretty much the bulk of the spell conditions done. Please see above for some little issues that need to be dealt with along with the invisible condition. I suggest running a `grep "invisible" ./*` in the `data/spells` directory and seeing the kinds of invisible you'll be replacing.

**Comment by l9f** [comment]
Updated first post checklist.

**Comment by TheGiddyLimit** [comment]
I'll check out Invisible later. For testing e.g. "{@condition Charmed}" you can use the [renderer demo page](https://5etools.com/demo.html), where you can edit some sample JSON and see the results. It's "working" if the link goes to where you'd expect!

This has been a massive help, thank you so much.

**Comment by TheGiddyLimit** [comment]
Invisibility is indeed a strange one. The condition refers to invisible "creatures," though, so I think I'll tag the ones that seem most relevant and call it good.
