### ISSUE TITLE
{@condition syntax}

### ISSUE THREAD

**Issue by l9f** [TheGiddyLimit/TheGiddyLimit.github.io#73]
There are a few instances of capitalized conditions in the spells text (see https://github.com/TheGiddyLimit/TheGiddyLimit.github.io/issues/66) 

Determine if there's a syntax change needed; i.e. have both `{@condition charmed}` AND a `{@condition Charmed}` for each condition that has a capital letter.

**Comment by TheGiddyLimit** [comment]
Both should work, currently.
