### ISSUE TITLE
tftyp typo pro duce

### ISSUE THREAD

**Issue by l9f** [TheGiddyLimit/TheGiddyLimit.github.io#84]
From Disc:

The Hidden Shrine of Tamoachan, written by Harold Johnson and Jeff R. Leason, made its debut under the title Lost Tamoachan at the Origins game convention in 1979, where it was used in the official D&D competition. The first published version of the adventure was pro duced in 1980.
the word produced is split in two

**Comment by TheGiddyLimit** [comment]
I'm not seeing it. `The first published version of the adventure was produced in 1980` as expected, for me. `grep "pro du" *` produces no results.

**Comment by l9f** [comment]
Hmmm. Let me go reproduce.
