### ISSUE TITLE
ToA Missing Images

### ISSUE THREAD

**Issue by TheGiddyLimit** [TheGiddyLimit/TheGiddyLimit.github.io#87]
chapter 2 p. 43 Bay of Chult: ship with dragon turtle replaced by the monter manual Dragon Turtle picture.

Chapter 2 p.57 Liara Portyr mug shot is missing

chapter 2 p.65 Jahaka Anchorage mugshots of the 3 pirate captains ,Elok Jaharwon, Laskilar and Zaroum Al-Saryak are missing

Chapter 3 p. 102 Bag of nails the demented tabaxi's bodyshot is missing

chapter 4 p. 117 Fenthaza's bodyshot is missing

Chapter 5 p. 127  spooky picture of the skeleton keys are missing

chapter 5 p. 144 Full body shot of Tomb gaurdian is missing

chapter 5 p. 158 Art of a four armed gargoyle is missing

Chapter 5 p. 162 art of 2 bodaks crawling out of a sphere of annihilation is missing

Chapter 5 p. 165 full body shot of a blind artist is missing

Chapter 5 p. 172 stone juggernaut art is missing

chapter 5 p. 176 skull chalice of ch'gakare
the rest of the pictures in that chapter are missing as well. Besides the maps offcourse
so p. 179, p. 181 and p. 185
and finally the 3 pictures of the magic items p. 206 ghost lantern, 207 Mask of the beast and 208 Ring of Winter.

**Comment by l9f** [comment]
Are you just wanting screen grabs of say, a PDF rip? Or are you looking for higher resolution?

**Comment by TheGiddyLimit** [comment]
I have some of the images; this is just a straight paste of a message I got. I need to go through and figure out which ones I'm missing, and which ones the ripper missed. 

If there are some missing, though (there's certainly one that I know of) I'd want e.g. D&D Beyond images, not screen-grabs.
