### ISSUE TITLE
[TYPO] Classes, Death Domain

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#89]
"Hades and He!" instead of "Hades and Hel".

The file (classes.json) is too big, I can't fix it myself with the online editor.

**Comment by TheGiddyLimit** [comment]
You've been doing all this in the online editor?! If you want to be able to edit anything, you can:
1. fork the repo
2. clone your fork to your local machine
3. edit files
4. commit, push to your fork on GitHub
5. make a pull request; it should automagically prompt you at the top of this repo's page, but if not, you can manually do it via pull requests -> compare across forks -> mine vs yours
