### ISSUE TITLE
[BUG] Global Search, Kiaransalee

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#90]
If you search "Kiaransalee" using the global search feature,
you get a link to ".../deities.html#kiaransalee_scag"
but this leads to an non existent page,
the real link is  ".../deities.html#kiaransalee_drow_scag".

This may be due to an outdated search index?
If that's the case there are probably other broken links to deities.

**Comment by TheGiddyLimit** [comment]
Yeah, that's exactly it. I don't always bother (or remember) to manually re-index it; the main site [here](https://5etools.com/) re-indexes whenever an update is deployed.
