### ISSUE TITLE
[BUG] Page layout for spells and creatures list

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#91]
Browser: Firefox 57 (Quantum).

Does this happen only to me? There's a chance this may be related to my specific OS
settings/libraries and, if so, apologies for wasting your time.

When I move the mouse pointer vertically on the index of spells or creatures,
passing from one entry to another, the "layout" of the list changes for a moment
before going back to normal*. Is it pretty annoying and tiring for the eyes.
Important note: this only happens if the list is long enough to require a scrollbar.

* EDIT: it goes back the normal once the mouse pointer stops.

In the spells page, you can even see a second empty row in the list of spells and sometimes
this layout change also affects the alignment/layout of the spell details on the right side of the page.
[See screenshot, the red arrows specifically](https://ibb.co/k6Tkp6).

Seems like a problem caused by hovering, as if when the mouse pointer hovers the layout
(the css style/details) used is slightly different from the default one.

**Comment by TheGiddyLimit** [comment]
Strange. Does the same thing happen in e.g. Chrome? Tried in Firefox on my (Windows) machine, and it seems fine. What OS are you using? Tried CTRL-F5?

There used to be an issue where list items with long text would expand when you hovered, in a manner (I'm guessing) like you described. I thought I had fixed it, and indeed have personally had no problem since, regardless of browser/OS. Might be related?

**Comment by Temp345** [comment]
Everything looks fine with Chromium, so it seems like it's Firefox fault.

I use Linux (a Debian based distro) with XFCE as desktop manager.
In the past I had problems with a UI library somehow related to windows' scrollbars
(hence the suspicion that it might be an issue with my system), but if it works fine
with another browser then I don't know what to think.

Anyway, if, as it seems, I am the only one with this issue don't waste time with it.
Firefox is my favourite browser (even if this last version seems very slow),
but I can live with it.

**Comment by TheGiddyLimit** [comment]
Alright. Only reason I can think of, is that Firefox doesn't support the CSS used for the custom scrollbars, so it'll let the window manager do whatever it pleases - which seems to be breaking it for you. Default scrollbars work just fine on Windows, although they're a little fat/ugly. Closing this, for now.
