### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#94]
Not a big deal, just wondering: is it possible to add a toggle somewhere to exclude
third party stuff from the omni search results?
Or, in order to not make you do any extra work, I'd like to ask if the index is generated
by a script and if would it be possible for an user to recreate it without the 3pp?
As final alternative, I know I could manually edit the index to delete those entries.

Keeping the UA version of officially published subclasses (e.g. Samurai) is a choice or an oversight?

Since we're here, [a little report:](https://thegiddylimit.github.io/items.html#amulet%20of%20proof%20against%20detection%20and%20location_dmg)
the term **divination** there refers to the school of magic, not to the specific spell, so it shouldn't
be a link (unless you can link to a filtered page with all divination spells, but that seems overzealous).

**Comment by TheGiddyLimit** [comment]
Toggle's a good idea, I'll add that.

Keeping legacy/UA versions of published classes is intentional, hence the hiding.

And there's no such thing as overzealous, it's now a link to a the spells page, pre-filtered for divination spells 😉
